### ISSUE TITLE
domain list request

### ISSUE THREAD

**Issue by angusding** [felixonmars/dnsmasq-china-list#101]
因为pull requests失败，没办法只好发到issue里了，两个需求请大神您考虑下能不能提供这样的list：
1）纯域名的list，就是“example.com”格式的列表，因为114那个dns延迟比较高（差不多是我这里的运营商提供的DNS的10倍），每次用这个列表，还得剥离多余的参数再加运营商的DNS。
2）另外还有个需求：能否提供个精简版的域名列表，能涵盖alexa top 500这个级别的国内域名就行，最好加上那些对应的cdn域名控制在1000个以内，因为这基本上能满足绝大多数人使用了，太多用不上反而影响系统运行效率。

**Comment by wongsyrone** [comment]
第一个需求用sed就能实现了，Win下也有类似的工具

**Comment by programmervy** [comment]
欢迎尝试我的[零 list 解决方案](https://github.com/programmervy/beautifuldnsd)哦 :-)

**Comment by felixonmars** [comment]
1) 运行 make raw 即可
2) 欢迎其他人做这件事，因为目前的列表我没有感觉到系统运行效率方面的问题。如果的确有运行效率的问题了，我会考虑优化 dnsmasq 或采用其他本地 relay 方案。

**Comment by angusding** [comment]
1）我需要在OpenWrt路由器上引用这个列表中的域名，但不想用它的DNS服务器，用make有些问题，所以要经过sed处理掉而显得麻烦了，不如直接用列表的域名来生成配置。
2）今年早些时候用这个列表的时候还不到2000个地址，最近爆增到11000多，升级后造成生成列表的时间也爆长，同时启动dnsmasq后占用的内存也比较多，对于嵌入式的系统性能影响较大，尤其在启动时将dnsmasq的运行结果加到系统日志后。

**Comment by angusding** [comment]
@programmervy 谢谢你，不过我需要使用dnsmasq，可能无法使用你的方案。

**Comment by felixonmars** [comment]
1) 用 make 有什么问题呢？这里的 Makefile 调用的依然是 sed 等基础命令而已……
2) 我不太清楚“生成配置文件”是什么操作。另外，内存占用具体多了多少呢？日志的问题是另一个问题了，建议关掉 dnsmasq 的日志。

**Comment by angusding** [comment]
OW本身没有make命令，生成其他格式的配置文件，比如：server=/0-6.com/x.y，因为114并不是对所有人都是最快的服务器，我自己做吧，替换下而已，只是感觉不如单纯的域名列表用起来干净。
日志是OW系统服务自动加载的，貌似太多会溢出自定义的日志缓存空间。
dnsmasq本身倒没开日志功能，但这个列表真心不错。加速效果明显。

**Comment by felixonmars** [comment]
嗯，这个项目叫 dnsmasq-china-list，本意是一个开箱即用的 dnsmasq 配置文件。提供 Makefile 只是让转化成其他格式稍微容易一些。

以后如果有精力的话，我会重构这个项目，拆分为不同理由加入的域名列表以定期自动验证。
