### ISSUE TITLE
Tomato路由器+DNScrypt，如何使用该项目？

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [felixonmars/dnsmasq-china-list#103]
请教，我使用的是tomato的路由器，开启了DNScrypt。总的来说使用正常，现在想使用这个项目。

我看到tomato路由器已经很强大了，自带了很多功能。里面也有dnsmasq模块，但我一直没用过。

我按照这个项目的usage说明，ssh到路由器（因为我不知道web界面那些模块怎么设置），自建了/etc/dnsmasq.d这个文件夹，scp了那两个关键文件。但问题是，

我重启了下路由器，发现我建的文件夹已经不见了（当初建的时候也是自动把我带到了/tmp/etc下）。

我在想，是不是可以直接在web界面里那个dnsmasq(custom)空白里填些什么就可以达到目的？

如果不是的话，应该怎么用呢？也不知道为什么root@192.168.1.1最后新建的dnsmasq.d会无法保存。

感谢。

**Comment by wongsyrone** [comment]
你需要将它保存在jffs2分区里面，使用conf-dir指定配置文件位置

**Comment by GreatBigWhiteWorld** [comment]
太感谢了！研究了一会什么是jffs后搞定！
访问国内网址明显快了。
dnscrypt跟这个项目配合使用真好啊。
