### ISSUE TITLE
Domain list changes in the google.china.conf.

### ISSUE THREAD

**Issue by legendtang** [felixonmars/dnsmasq-china-list#111]
````
nslookup redirector.gvt1.com 114.114.114.114
服务器:  public1.114dns.com
Address:  114.114.114.114

非权威应答:
名称:    redirector.gvt1.com
Addresses:  2404:6800:4002:803::100e
          203.208.49.174
          203.208.49.164
          203.208.49.163
          203.208.49.168
          203.208.49.169
          203.208.49.160
          203.208.49.167
          203.208.49.165
          203.208.49.166
          203.208.49.162
          203.208.49.161
````

Maybe more sub-domains will be discovered.

Some domains like `dl.google.com` do not point to Google CN servers at this time. But it's still strongly recommended to leave them in the list.

**Comment by felixonmars** [comment]
Thanks, added. Please let me know when you find more :)

**Comment by legendtang** [comment]
A good news for this. Now if you `dig redirector.gvt1.com @114.114.114.114` and you are not living in Beijing, Shanghai and Canton, you will find those IPs don't begin with 203 anymore but have turned to each province's specified Google CDN address. However, most ISP's DNS will not result like this atm.

We need more domain names like this, I suggest we should do further investigation together. It may be a good start for Google Play :)

**Comment by felixonmars** [comment]
That's interesting indeed. Thanks for letting me know :)
