### ISSUE TITLE
四川移动 bogus nxdomain 

### ISSUE THREAD

**Issue by EricDiao** [felixonmars/dnsmasq-china-list#113]
183.221.242.172
当我执行 dig 一个不存在的域名时，例如`dig askldjssk.com`时的响应为：

> pi@CTU:~/dnsmasq-china-list $ dig askldjssk.com
> 
> ; <<>> DiG 9.9.5-9+deb8u4-Raspbian <<>> askldjssk.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36145
> ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;askldjssk.com.            IN  A
> 
> ;; ANSWER SECTION:
> askldjssk.com.     0   IN  A   183.221.242.172
> 
> ;; Query time: 10 msec
> ;; SERVER: 183.221.253.100#53(183.221.253.100)
> ;; WHEN: Sat Jan 30 16:34:20 CST 2016
> ;; MSG SIZE  rcvd: 58

这会将我带到搜狗的搜索引擎。
可以加在列表中：
`#China Mobile Sichuan`
`bogus-nxdomain=183.221.242.172`

**Comment by lilydjwg** [comment]
我发现邮件通知里，IP 地址的点全没了……

**Comment by felixonmars** [comment]
已添加，谢谢！
