### ISSUE TITLE
dl.google.com no longer resolved to Google China IP

### ISSUE THREAD

**Issue by wyf88** [felixonmars/dnsmasq-china-list#114]
root@WNDR4300:~# nslookup dl.google.com 114.114.115.119
Server:    114.114.115.119
Address 1: 114.114.115.119 anti-malware-2.114dns.com

Name:      dl.google.com
Address 1: 2404:6800:4005:800::200e hkg07s21-in-x0e.1e100.net
Address 2: 216.58.221.46 hkg08s13-in-f14.1e100.net

root@WNDR4300:~# ping dl.google.com
PING dl.google.com (216.58.199.14): 56 data bytes
♥
--- dl.google.com ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss

**Comment by EricDiao** [comment]
it is resolved to ip located in beijing now but it seems that china mobile sichuan blocked those ips.

ericdiao@ericdiao-ThinkPad:~$ dig dl.google.com

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> dl.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24251
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dl.google.com.			IN	A

;; ANSWER SECTION:
dl.google.com.		156121	IN	CNAME	dl.l.google.com.
dl.l.google.com.	252	IN	A	203.208.39.195
dl.l.google.com.	252	IN	A	203.208.39.196
dl.l.google.com.	252	IN	A	203.208.39.199
dl.l.google.com.	252	IN	A	203.208.39.197
dl.l.google.com.	252	IN	A	203.208.39.200
dl.l.google.com.	252	IN	A	203.208.39.198
dl.l.google.com.	252	IN	A	203.208.39.201
dl.l.google.com.	252	IN	A	203.208.39.193
dl.l.google.com.	252	IN	A	203.208.39.206
dl.l.google.com.	252	IN	A	203.208.39.194
dl.l.google.com.	252	IN	A	203.208.39.192

;; Query time: 47 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Sun Mar 06 21:33:32 CST 2016
;; MSG SIZE  rcvd: 237

ericdiao@ericdiao-ThinkPad:~$ ping dl.google.com
PING dl.l.google.com (203.208.39.192) 56(84) bytes of data.
^C
--- dl.l.google.com ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 4999ms

**Comment by wyf88** [comment]
Yes, I can confirm this. It is resolved to Google Beijing IP. No problem for China Telecom and Unicom.
