### ISSUE TITLE
对目前列表的补充

### ISSUE THREAD

**Issue by tomasen** [felixonmars/dnsmasq-china-list#116]
我不太确定怎样才是比较合适的提交更新的方式。

这是我对目前列表的补充，检测的方式是根据是否使用了中国的dns
[accelerated-domains-20160203.china.conf.zip](https://github.com/felixonmars/dnsmasq-china-list/files/117953/accelerated-domains-20160203.china.conf.zip)

我使用的检测代码： https://github.com/tomasen/dnsmasq-china-list

**Comment by EricDiao** [comment]
可以pull request.

2016-02-05 2:07 GMT+08:00 SHEN SHENG <notifications@github.com>:

> 我不太确定怎样才是比较合适的提交更新的方式。
>
> 这是我对目前列表的补充，检测的方式是根据是否使用了中国的dns
> accelerated-domains-20160203.china.conf.zip
> <https://github.com/felixonmars/dnsmasq-china-list/files/117953/accelerated-domains-20160203.china.conf.zip>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixonmars/dnsmasq-china-list/issues/116>.
>



-- 
From 刁子豪
Website: me.ericdiao.com
E-mail:  ericdiao.mail@gmail.com <ericdiao.mail@gmail.com>
            hi@ericdiao.com

**Comment by CNMan** [comment]
能主动批量检测么？
https://github.com/opendns/public-domain-lists
top10000的历史记录除去.cn
[nondotcn.txt](https://github.com/felixonmars/dnsmasq-china-list/files/119159/nondotcn.txt)

**Comment by tomasen** [comment]
another update

[accelerated-domains-20160204.china.conf.zip](https://github.com/felixonmars/dnsmasq-china-list/files/119680/accelerated-domains-20160204.china.conf.zip)

也许积累更多时再抽时间合并后一起pr过来

**Comment by felixonmars** [comment]
有提供一个简单的 updater.py 脚本，可以用于添加一个或多个条目并排序。

**Comment by felixonmars** [comment]
有一个小问题：你的列表里好像包括了很多 NS 为 `01~04.dnsv.jp.` 的域名，这四台机器都不在境内哦。

**Comment by tomasen** [comment]
没注意还有.jp
 我是用dnsv的关键字匹配的

过几天我重新整理下再提交

沈晟|Tomasen

**Comment by tomasen** [comment]
[accelerated-domains-20160217.china.zip](https://github.com/felixonmars/dnsmasq-china-list/files/134005/accelerated-domains-20160217.china.zip)

更新下修正后的结果

另外建议将 update.py 的用法也能写到 readme 中

**Comment by felixonmars** [comment]
谢谢。

我有个更复杂的重构计划，来加入持续验证等功能，不过暂时还没有实现多少。

**Comment by tenwx** [comment]
列表越来越长了，这么做终究不够优雅，希望能有一个更好的国内域名加速识别方式，比如一个域名解析时同时进行114.114.114.114和8.8.8.8解析，然后判断解析出来的ip是否在国内，如果是的话缓存起来，这样就不用一直维护一个静态列表了。只是抛砖引玉下哈

**Comment by felixonmars** [comment]
你可以把这里维护的列表当作缓存的初始值 :)

**Comment by tomasen** [comment]
应该是行不通的，特别是对那些被gfw篡改了dns记录的域名

沈晟|Tomasen

**Comment by tenwx** [comment]
那如果采用tcp方式查询dns能解决劫持问题吧

**Comment by programmervy** [comment]
@tenwx TCP 可以被重置的。你可以试试 [beautifuldnsd](https://github.com/programmervy/beautifuldnsd)。

**Comment by tenwx** [comment]
还有一个问题就是，如果只是针对智能翻墙的话，采用中国域名白名单走114.114.114.114其余用8.8.8.8好，还是用gfwlist黑名单走8.8.8.8其余走114.114.114.114好？

**Comment by felixonmars** [comment]
我选择用白名单的原因是，很多境外服务器即使没有被墙，访问也很慢。

**Comment by tomasen** [comment]
[accelerated-domains.china.0310.zip](https://github.com/felixonmars/dnsmasq-china-list/files/166566/accelerated-domains.china.0310.zip)

update

**Comment by felixonmars** [comment]
已更新的部分已经全部处理。
