### ISSUE TITLE
对于cname在cdn加速应用上的疑问

### ISSUE THREAD

**Issue by tenwx** [felixonmars/dnsmasq-china-list#118]
记得在#38 的issue里你提到过如果域名解析出来的是cname，那么必须要同时添加原域名和cname域名，否则只加cname起不到加速效果。现在很多网站都用了cdn加速，如果只需要关注实际的cname域名的话我相信会大大减少域名列表数目，不过经过测试貌似的确不行。请问这是什么原理？有相关的资料吗？

**Comment by felixonmars** [comment]
因为你用的远端递归解析服务器返回给你的结果是最终结果，解析 CNAME 记录的过程在远端完成，因此不会匹配到本地规则。

如果你在本地搭建递归解析服务器，则可以用到这些规则，但代价是大部分域名解析速度变慢，因为本地的域名缓存远少于公共的递归解析服务器。另一方面，一些域名会根据连到权威域名服务器的 IP 段返回不同的 CNAME/A 记录，因此本地的递归解析服务器需要配合更加复杂的 IP 规则才能使结果尽量优化到接近直接使用远端递归服务器的结果。

原理可以参考一般对递归解析服务器的介绍。

**Comment by tenwx** [comment]
谢谢
