### ISSUE TITLE
在使用自动检测机制添加域名？

### ISSUE THREAD

**Issue by blahgeek** [felixonmars/dnsmasq-china-list#121]
注意到近期在accelerated-domains.china.conf添加了一大批比较冷门的域名，我猜似乎在使用自动的脚本批量添加？

对此我有一些疑虑，我猜不是所有的国内外DNS返回不同结果的域名都是国内访问质量更好的，甚至有些站内容都会不一样，还是需要手动添加比较科学？

另外，请问这些域名都是从哪里得到的呢？

thx~

**Comment by felixonmars** [comment]
自动添加的基本都是 NS 服务器在国内的域名，作用主要是加快解析速度。自动添加的时候已经特意过滤掉了解析结果不同的部分，经过手动比对后再根据情况加入。

域名来源有很多来自 #116

**Comment by blahgeek** [comment]
噢… 如果要把所有NS服务器在国内的域名都加入这个列表的话，这个列表未免太大了吧？更新量会很大，并且（应该）也会影响dnsmasq的处理速度吧

我个人认为更加合理的目标只是把常用域名（比如top1000）中有CDN导致使用国外DNS会影响页面访问速度的域名加进来就可以了，而解析速度不需要考虑

**Comment by felixonmars** [comment]
以后有考虑分开。现在如果遇到 dnsmasq 的处理速度问题，就该改改 dnsmasq 了 :)

**Comment by underleo** [comment]
目前是3万4千多条，在我的wzr1750dphd上貌似没有出现性能问题。
也注意到了很多以数字开头的域名，貌似铁定是长期冷板凳的，例如"00-xx.net"这类，赶脚是可以想想如何缩小下列表了。
BTW，这个项目超好啊，之前想在"http://www.alexa.com/topsites/countries/CN"这里抓域名，但貌似现在抓不出来了。。
话说，如果能从上面那个知名机构把域名抓出来，我感觉基本够用了。95%吧 :-)
ps: dd-wrt 27085 kongac
