### ISSUE TITLE
对google.china.conf的一点补充

### ISSUE THREAD

**Issue by ygqsgm** [felixonmars/dnsmasq-china-list#122]
> server=/cache.pack.google.com/114.114.114.114

> server=/kh.google.com/114.114.114.114

> server=/khmdb.google.com/114.114.114.114

> server=/safebrowsing-cache.google.com/114.114.114.114

1.Google 下载 软件 用的 具体用途不详
2.3. 为Google Earth 数据读取
4.Googler Earth访问时亦有请求，作用不详，有个与之对应的safebrowsing.google.com(cname:sb.l.google.com)

**Comment by ygqsgm** [comment]
dig +tcp @208.67.222.222 -p 443 cache.pack.google.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.2 <<>> +tcp @208.67.222.222 -p 443 cache.pack.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61910
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;cache.pack.google.com.		IN	A

;; ANSWER SECTION:
cache.pack.google.com.	1200	IN	CNAME	redirector.c.pack.google.com.
redirector.c.pack.google.com. 300 IN	A	203.208.40.40
redirector.c.pack.google.com. 300 IN	A	203.208.40.32
redirector.c.pack.google.com. 300 IN	A	203.208.40.37
redirector.c.pack.google.com. 300 IN	A	203.208.40.35
redirector.c.pack.google.com. 300 IN	A	203.208.40.38
redirector.c.pack.google.com. 300 IN	A	203.208.40.36
redirector.c.pack.google.com. 300 IN	A	203.208.40.34
redirector.c.pack.google.com. 300 IN	A	203.208.40.39
redirector.c.pack.google.com. 300 IN	A	203.208.40.33
redirector.c.pack.google.com. 300 IN	A	203.208.40.41
redirector.c.pack.google.com. 300 IN	A	203.208.40.46

;; Query time: 174 msec
;; SERVER: 208.67.222.222#443(208.67.222.222)
;; WHEN: Sun Apr 03 15:01:39 CST 2016

----------------------------------------------------------------------
 dig +tcp @208.67.222.222 -p 443 kh.google.com        

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.2 <<>> +tcp @208.67.222.222 -p 443 kh.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29629
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;kh.google.com.			IN	A

;; ANSWER SECTION:
kh.google.com.		345600	IN	CNAME	keyhole.l.google.com.
keyhole.l.google.com.	300	IN	A	203.208.41.39
keyhole.l.google.com.	300	IN	A	203.208.41.41
keyhole.l.google.com.	300	IN	A	203.208.41.34
keyhole.l.google.com.	300	IN	A	203.208.41.33
keyhole.l.google.com.	300	IN	A	203.208.41.40
keyhole.l.google.com.	300	IN	A	203.208.41.37
keyhole.l.google.com.	300	IN	A	203.208.41.46
keyhole.l.google.com.	300	IN	A	203.208.41.38
keyhole.l.google.com.	300	IN	A	203.208.41.35
keyhole.l.google.com.	300	IN	A	203.208.41.32
keyhole.l.google.com.	300	IN	A	203.208.41.36

;; Query time: 522 msec
;; SERVER: 208.67.222.222#443(208.67.222.222)
;; WHEN: Sun Apr 03 15:02:10 CST 2016
;; MSG SIZE  rcvd: 242

-------------------------------------------------------------------------------------
dig +tcp @208.67.222.222 -p 443 khmdb.google.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.2 <<>> +tcp @208.67.222.222 -p 443 khmdb.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63646
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;khmdb.google.com.		IN	A

;; ANSWER SECTION:
khmdb.google.com.	345600	IN	CNAME	khmdb.l.google.com.
khmdb.l.google.com.	300	IN	A	203.208.40.33
khmdb.l.google.com.	300	IN	A	203.208.40.39
khmdb.l.google.com.	300	IN	A	203.208.40.36
khmdb.l.google.com.	300	IN	A	203.208.40.41
khmdb.l.google.com.	300	IN	A	203.208.40.37
khmdb.l.google.com.	300	IN	A	203.208.40.32
khmdb.l.google.com.	300	IN	A	203.208.40.34
khmdb.l.google.com.	300	IN	A	203.208.40.40
khmdb.l.google.com.	300	IN	A	203.208.40.35
khmdb.l.google.com.	300	IN	A	203.208.40.46
khmdb.l.google.com.	300	IN	A	203.208.40.38

;; Query time: 162 msec
;; SERVER: 208.67.222.222#443(208.67.222.222)
;; WHEN: Sun Apr 03 15:03:24 CST 2016
;; MSG SIZE  rcvd: 243

-----------------------------------------------------------------------------------------
dig +tcp @208.67.222.222 -p 443 safebrowsing-cache.google.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.2 <<>> +tcp @208.67.222.222 -p 443 safebrowsing-cache.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57416
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;safebrowsing-cache.google.com.	IN	A

;; ANSWER SECTION:
safebrowsing-cache.google.com. 597264 IN CNAME	safebrowsing.cache.l.google.com.
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.39
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.46
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.34
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.36
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.40
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.41
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.38
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.33
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.32
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.35
safebrowsing.cache.l.google.com. 300 IN	A	203.208.41.37

;; Query time: 241 msec
;; SERVER: 208.67.222.222#443(208.67.222.222)
;; WHEN: Sun Apr 03 15:03:53 CST 2016
;; MSG SIZE  rcvd: 269

**Comment by felixonmars** [comment]
多谢，已添加～

**Comment by ygqsgm** [comment]
继续补充
server=/khm.google.com/119.29.29.29
server=/khm0.google.com/119.29.29.29
server=/khm1.google.com/119.29.29.29
server=/khm2.google.com/119.29.29.29
server=/khm3.google.com/119.29.29.29

@felixonmars

**Comment by ygqsgm** [comment]
以及由bandaid-redirector.l.google.com 重定向的一系列域名似乎都回归到了中国服务器。
如：v24.nonxt8.c.android.clients.google.com，
但是这些域名对应功能似乎有不少已经失效或者只是适用于旧版本的应用

**Comment by felixonmars** [comment]
谢谢，我暂时加上了 `c.android.clients.google.com`，有一定误判，但是总体应该还好。测试一段时间看看怎么样 :)
