### ISSUE TITLE
Produce too much log

### ISSUE THREAD

**Issue by sopium** [felixonmars/dnsmasq-china-list#124]
Dnsmasq logs every entry in the list every time it starts/reloads, thus created an `/var/log/syslog` as large as 0.5GiB on my router.

Users should be warned of this problem.

There is unfortunately no easy fix. Maybe we should contact 
[dnsmasq-discuss](mailto:dnsmasq-discuss@lists.thekelleys.org.uk).

**Comment by felixonmars** [comment]
I use systemd and it was limited by default, so I never paid attention to it. Please let me know if there is a fix and I'll update README accordingly :)

**Comment by lilydjwg** [comment]
@felixonmars in fact journald will be more affected, because it shares the limit among all the logs. With syslog, it's easier to filter out and rotate dnsmasq's logs so it won't occupy too much space.

**Comment by sopium** [comment]
I didn't get any response from [dnsmasq-discuss](http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2016q2/010464.html).

Here is how to discard these logs with rsyslog:

In `/etc/rsyslog.conf` prepend, or create `/etc/rsyslog.d/10-dnsmasq-china-list.conf` and add
```
:msg, contains, "using nameserver 114.114.114.114#53 for" ~
```

There doesn't seem to be an easy way to filter logs in journald though.

**Comment by sopium** [comment]
Simon Kelley has fixed it in dnsmasq([link](http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2016q2/010510.html)). Closing.

**Comment by felixonmars** [comment]
Thanks for the update!
