### ISSUE TITLE
发现列表太大导致dnsmasq的cpu过高

### ISSUE THREAD

**Issue by atmouse-** [felixonmars/dnsmasq-china-list#126]
影响解析速度么？

**Comment by felixonmars** [comment]
嵌入式设备吗？我这里没有测试环境，不清楚有多大影响。我这边的网关是 Atom D525 自己搭的软路由，尚未发现 CPU 过高（最多 5%）问题，解析速度也很稳定（dnsmasq 反应 <1ms）

**Comment by xiaoyangde** [comment]
我倒是遇到过列表损坏（或者可能是没有下载完全），导致dnsmasq启动失败的情况，有没有什么检测列表语法的办法？

**Comment by wongsyrone** [comment]
如果有兴趣可以尝试https://github.com/infinet/dnsmasq

**Comment by atmouse-** [comment]
不是嵌入式，就服务器虚拟机，请求量比较大，而且由于功能需求我不得不关闭dnsmasq的cache。
其实就是需要这个功能。
感觉dnsmasq没法用上多线程？cpu最多也就一个核心高，现在我在想单台上开多个然后用lvs均衡负载

**Comment by atmouse-** [comment]
用这个 https://github.com/infinet/dnsmasq 好些了

**Comment by underleo** [comment]
dd-wrt kong build 27085 没发现CPU负荷高问题，解析速度灰常快。

**Comment by atmouse-** [comment]
算是解决了吧
