### ISSUE TITLE
Most of domains listed in `google.china.conf`are being polluted.

### ISSUE THREAD

**Issue by legendtang** [felixonmars/dnsmasq-china-list#129]
As is said in title, 114DNS is over, other DNS providers seemed fine.

P.S. China Telecom, WH

**Comment by felixonmars** [comment]
Confirmed. Since it's not the first time for me, I am switching to alidns for google domains by default.

**Comment by felixonmars** [comment]
Oh crap, it's not that easy:

```
$ dig www.google-analytics.com @223.6.6.6

; <<>> DiG 9.10.4-P1 <<>> www.google-analytics.com @223.6.6.6
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6413
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google-analytics.com.      IN      A

;; ANSWER SECTION:
www.google-analytics.com. 15    IN      CNAME   www-google-analytics.l.google.com.
www-google-analytics.l.google.com. 15 IN A      59.24.3.173

;; Query time: 27 msec
;; SERVER: 223.6.6.6#53(223.6.6.6)
;; WHEN: Tue Jun 14 21:04:39 CST 2016
;; MSG SIZE  rcvd: 102
```

**Comment by legendtang** [comment]
@felixonmars Yes, alidns pollutes those too though it was okay this afternoon. ISP DNS and DNSPod+ seems okay. However, maybe it is the DNS cache that hasn't been updated if it is global polluting behavior.

You should try a `git push --force` :XD

**Comment by felixonmars** [comment]
はい <(=^_^=)>

**Comment by lilydjwg** [comment]
Not confirmed here. Maybe it's just some network  issues or routing changes make the server chooses abroad answers.

**Comment by lilydjwg** [comment]
Also, 8,8.8.8 answers it just fine.

**Comment by felixonmars** [comment]
Well, it's affecting ~half of China:

![2016-06-14-211305-a0f053](https://cloud.githubusercontent.com/assets/1006477/16047286/20032d3a-3215-11e6-8a96-b4fffef93a7b.png)

**Comment by lilydjwg** [comment]
@felixonmars 你这除了香港之外没一个解析得对的啊。我刚刚在奇云测上测了一下，都没问题。但是我本地现在解析不出来了……

**Comment by felixonmars** [comment]
我测试的是 www.google.com，解析到香港 Google 的 IP 就算对了。现在已经恢复了。

**Comment by legendtang** [comment]
It seems the issue has been resolved after several months' monitoring.
