### ISSUE TITLE
列表里面有一些不是必需的项目

### ISSUE THREAD

**Issue by liyvhg** [felixonmars/dnsmasq-china-list#130]
目前列表变得越来越大, 在普通路由器上较难加载了.
简单看了列表里面新增的一些域名, 有一部分是无需添加进本列表的: 例如tbsandbox.com.
其标志为:该域名的DNS请求未区分国籍, 全球任意DNS服务器解析出来的结果都是同一个/同一组.
建议此类型的域名不再添加进列表, 以增强列表质量.

**Comment by felixonmars** [comment]
加入这部分域名的理由是，因为其权威 NS 服务器在境内，用境内递归 DNS 服务器解析仍然会更快。现在有计划对这两种情况进行区分，暂时还没有提交上来。

**Comment by hdstar2009** [comment]
有没有什么项目只提供国内大型网站或者在国外有cdn的那些网站的国内域名列表？
我觉得我需要的是这种。

至于刚刚看到这个项目的3w多中国域名，绝大多数从来没见过估计这辈子也不会去访问的网站，感觉用不上。3w多条记录不知道放到路由器的dnsmasq上会是什么结果。

**Comment by felixonmars** [comment]
>有没有什么项目只提供国内大型网站或者在国外有cdn的那些网站的国内域名列表？
我上面有回复过，*现在有计划对这两种情况进行区分，暂时还没有提交上来。*

>3w多条记录不知道放到路由器的dnsmasq上会是什么结果。
你可以试一试，很多人都是这样在用……

**Comment by vempx** [comment]
感谢作者，我一直在用，不过说实话条目太多了之后，我的N66U真是撑不住了……dnsmasq占用率长期高达60-70。换到AC68U之后倒是不存在这个问题了，但是mips的老路由器确实有点吃不消 ：）

**Comment by hdstar2009** [comment]
抛砖引玉，我现在用的一些国内大型网站才指定用国内dns解析的列表，其他网站谷歌dns解析：
.qq.com,
.weixin.com,
.taobao.com,
.alibabadns.com,
.tbcache.com,
.taobao-img.com,
.sina.com,
.baidu.com,
.tencent.com,
.txcdn.com,
.alipay.com,
.sohu.com,
.netease.com,
.youku.com,
.jd.com,
.jdcdn.com;

在 2016年7月26日 下午12:19，vempx <notifications@github.com>写道：

**Comment by vempx** [comment]
> 抛砖引玉，我现在用的一些国内大型网站才指定用国内dns解析的列表，其他网站谷歌dns解析：
> .qq.com,
> .weixin.com,
> .taobao.com,
> .alibabadns.com,
> .tbcache.com,
> .taobao-img.com,
> .sina.com,
> .baidu.com,
> .tencent.com,
> .txcdn.com,
> .alipay.com,
> .sohu.com,
> .netease.com,
> .youku.com,
> .jd.com,
> .jdcdn.com;

直接添加这些常用网站的主域名确实是可以，但是在主域名的背后其实还有各种奇奇怪怪的cdn域名的，这些东西才是最头大的部分……

**Comment by skyline75489** [comment]
现在这个列表是有点大了，感觉一般路由器可能会受不了，在电脑上跑应该还是没啥压力的。

我记得 dnsmasq 内部实现里面，规则这部分的条数认为是在 5 万条左右，再大的话性能貌似会下降。目前看 3 万条还是可以接受的。

**Comment by comicfans** [comment]
可以在比较慢的dnsmasq前面再加一层unbound或者pdnsd，可以解决这个问题。

**Comment by WalterMa** [comment]
不知道有没有考虑过选出top1000条的规则，估计就能涵盖90%以上使用域名了

**Comment by Myer921** [comment]
如果可以的话，对于性能不高的路由单独做个列表
原有列表会慢慢增加，这是我的建议
在安装的时候分别设置两个选项
lite和full（

PS：我家路由还算可以，重启倒是没问题....

**Comment by cokebar** [comment]
可以在管理列表中域名时候 给域名划分类别和等级。比如根据网站PR值之类的划分等级，根据是否有CDN、是否有国内、国外CDN、NS是国内还是国外等等来划分类别。当然，整理3万条还是很耗时间的

**Comment by wbsdty331** [comment]
对，我也赞同 @Myer921 的看法，做一个 Lite 版和 Full 版，各取所需

**Comment by hdstar2009** [comment]
隔了这么久时间，我来重新回复下。
实际上这个名单方式还是不方便，最方便还是直接国内ip不走，国外ip全走代理。反正现在vps都便宜，不需要考虑什么节省流量啥的。

2017-05-01 14:52 GMT+08:00 Liu Yixuan <notifications@github.com>:

**Comment by cokebar** [comment]
@hdstar2009 这个名单很大程度上的意义在于 避免某些国内域名被解析到国外IP上

**Comment by Myer921** [comment]
@hdstar2009 我正是这么做的，不过我的国际出口带宽明显没有国内稳定
不然我连dns都8888 8844了

**Comment by zw963** [comment]
> 感谢作者，我一直在用，不过说实话条目太多了之后，我的N66U真是撑不住了……dnsmasq占用率长期高达60-70。换到AC68U之后倒是不存在这个问题了，但是mips的老路由器确实有点吃不消 ：）

我 AC66U，感觉还行

**Comment by pexcn** [comment]
也许这个可以解决？https://www.v2ex.com/t/172010
