### ISSUE TITLE
能否把那些有国外cdn的国内域名做个表，不需要全部中国域名

### ISSUE THREAD

**Issue by hdstar2009** [felixonmars/dnsmasq-china-list#132]
正如他人所说，现在的中国域名列表越来越大，实际很多没必要，因为国外dns解析很多国内域名和国内dns解析这些国内域名是一样的。

只有新浪 淘宝 网易 腾讯等大型网站才会因为国外cdn的关系导致国内和国外dns解析的结果不一样。
实际上整理这部分域名给国内dns用就可以了。

其他大多数就算用国外dns解析花费的时间相对载入网站页面等等也可以忽略吧。何况如果加上pdnsd这样的本地缓存。

**Comment by felixonmars** [comment]
请看我在 https://github.com/felixonmars/dnsmasq-china-list/issues/130 中的回复。
