### ISSUE TITLE
PTR query questions

### ISSUE THREAD

**Issue by ziyilu** [felixonmars/dnsmasq-china-list#135]
Hi,

Thanks for the list. 

Here is what I did:
I put the China domain (or with China CDN) DNS queries to China DNS server (114.114.114.114), and put those domains not in the list to 8.8.8.8 (via VPN).

the conf file looks like,
server=/qq.com/114.114.114.114
....
server=8.8.8.8 (last line)

Everything works fine except one thing,
example: the client successfully get IP address from www.qq.com (from 114.114.114.114), then the client will send PTR query to DNS server, DNS server does not corresponding PTR query server, so it will forward all PTR query to 8.8.8.8, which is not correct.

Any work around to this?

Thanks,
Jerry

**Comment by lilydjwg** [comment]
This shouldn't cause any issues except performance ones.

You can route all PTR queries to 114.114.114.114. Or route by IP ranges.
