### ISSUE TITLE
CloudXNS 的 DNS 服务器解析

### ISSUE THREAD

**Issue by t123yh** [felixonmars/dnsmasq-china-list#137]
lv3ns1.ffdns.net
lv3ns2.ffdns.net
lv3ns3.ffdns.net
lv3ns4.ffdns.net
这几个域名有时候会解析到国外，希望加入列表。

**Comment by felixonmars** [comment]
根域名 `ffdns.net` 已经在列表里，不需要单独添加子域名了。
