### ISSUE TITLE
bogus nxdomain

### ISSUE THREAD

**Issue by CNMan** [felixonmars/dnsmasq-china-list#145]
辽宁联通
lndnserror1.wo.com.cn.  1288    IN      A       60.19.29.21
lndnserror2.wo.com.cn.  1800    IN      A       60.19.29.22
lndnserror3.wo.com.cn.  1800    IN      A       60.19.29.23
lndnserror4.wo.com.cn.  1800    IN      A       60.19.29.24
lndnserror5.wo.com.cn.  1800    IN      A       60.19.29.25
lndnserror6.wo.com.cn.  1800    IN      A       60.19.29.26
lndnserror7.wo.com.cn.  1800    IN      A       60.19.29.27
山西联通
sxdnserror1.wo.com.cn.  1286    IN      A       221.204.244.36
sxdnserror2.wo.com.cn.  1800    IN      A       221.204.244.37
sxdnserror3.wo.com.cn.  1800    IN      A       221.204.244.38
sxdnserror4.wo.com.cn.  1800    IN      A       221.204.244.39
sxdnserror5.wo.com.cn.  1800    IN      A       221.204.244.40
sxdnserror6.wo.com.cn.  1800    IN      A       221.204.244.41
天津联通
tjdnserror1.wo.com.cn.  1282    IN      A       218.68.250.117
tjdnserror2.wo.com.cn.  1800    IN      A       218.68.250.118
tjdnserror3.wo.com.cn.  1800    IN      A       218.68.250.119
tjdnserror4.wo.com.cn.  1800    IN      A       218.68.250.120
tjdnserror5.wo.com.cn.  1800    IN      A       218.68.250.121
陕西西安电信
125.76.239.244
125.76.239.245

**Comment by felixonmars** [comment]
All added. Many thanks!
