### ISSUE TITLE
收集各地运营商的 bogus nxdomain ip

### ISSUE THREAD

**Issue by CNMan** [felixonmars/dnsmasq-china-list#148]
在v2ex发了个[主题](https://www.v2ex.com/t/333204)，希望能收集更多的bogus nxdomain ip

批处理是查询不存在的lndnserror8.wo.com.cn~lndnserror57.wo.com.cn

**Comment by CNMan** [comment]
nmwhfx反馈的: 中国内蒙古呼和浩特联通
202.99.254.230
202.99.254.231

补充
nmdnserror2.wo.com.cn.  1800    IN      A       202.99.254.231
nmdnserror3.wo.com.cn.  1800    IN      A       202.99.254.232
nmdnserror4.wo.com.cn.  1800    IN      A       202.99.254.230

**Comment by felixonmars** [comment]
谢谢，已添加

**Comment by CNMan** [comment]
河南联通
hndnserror1.wo.com.cn.  1800    IN      A       218.28.144.36
hndnserror2.wo.com.cn.  1800    IN      A       218.28.144.37
hndnserror3.wo.com.cn.  1800    IN      A       218.28.144.38
hndnserror4.wo.com.cn.  1800    IN      A       218.28.144.39
hndnserror5.wo.com.cn.  1800    IN      A       218.28.144.40
hndnserror6.wo.com.cn.  1800    IN      A       218.28.144.41
hndnserror7.wo.com.cn.  1800    IN      A       218.28.144.42

**Comment by felixonmars** [comment]
刚刚加上了 :)

**Comment by CNMan** [comment]
好，希望能有更多人“当地人”反馈:)

**Comment by CNMan** [comment]
http://www.ipip.net/dns.php
http://www.17ce.com/
http://ping.chinaz.com/

从以上在线工具整理的一些

安徽电信
61.191.206.4
湖南电信
124.232.132.94
江西电信
61.131.208.210
61.131.208.211
广西电信
113.12.83.4
113.12.83.5
云南电信
220.165.8.172
220.165.8.174
江苏电信
202.102.110.204
海南电信
202.100.220.54
甘肃电信
202.100.68.117
湖南电信
124.232.132.94
河北电信
222.221.5.204

安徽联通
112.132.230.179

陕西移动
211.137.130.101
江西移动
223.82.248.117
江苏移动
183.207.232.253
安徽移动
120.209.138.64
西藏移动
111.11.208.2
山东移动
120.192.83.163
青海移动
211.138.74.132
四川移动
183.221.250.11
山西移动
211.138.102.198
广东移动
221.179.46.190

**Comment by felixonmars** [comment]
谢谢，已添加。

**Comment by CNMan** [comment]
maojy1989 反馈的上海移动
211.136.113.1

**Comment by mewsf** [comment]
山东电信 219.146.13.36

**Comment by CNMan** [comment]
@felixonmars FlyingLion 反馈的
```
# Guangdong Mobile
bogus-nxdomain=221.179.46.194

# Yunnan Mobile
bogus-nxdomain=183.224.40.24
```

**Comment by felixonmars** [comment]
谢谢，这三个已添加。

**Comment by CNMan** [comment]
@felixonmars FlyingLion 反馈的
```
#Beijing Unicom
bogus-nxdomain=61.135.22.21
```

**Comment by sy618** [comment]
广东移动
bogus-nxdomain=221.179.46.193
bogus-nxdomain=221.179.46.194

**Comment by 1plus-1** [comment]
下面的不是nxdomain， 但每天头几次的访问有可能被resolve到下面的地址，加到nxdomain里应该也可以解决
http://welcome.jsinfo.net/cas/view/c/32,9712,&amp;j?id=7cc685baa71cLK36I3fNw3bmmr_NVybQFycIYb3D1r09lDZmDCdbsbN1EKk9MpN1ppc
221.231.148.252

**Comment by anglabace** [comment]
名称:    lndnserror42.wo.com.cn
Address:  220.250.64.225
