### ISSUE TITLE
精简非必需条目的accelerated-domains.china.conf

### ISSUE THREAD

**Issue by llpub** [felixonmars/dnsmasq-china-list#150]
accelerated-domains.china.conf提供了庞大的国内 urls, 不过里面有些url用权威nameserver解析和用大陆nameserver(如114)解析的结果是一样的, 可以去掉以精简这个accelerated-domains.china.conf的数量. 
这里提供一个精简过的list: lite_accelerated-domains.china.conf (4702行, 请自行去掉后缀.txt)
[lite_accelerated-domains.china.conf.txt](https://github.com/felixonmars/dnsmasq-china-list/files/701589/lite_accelerated-domains.china.conf.txt)

原理就是对accelerated-domains.china.conf的url查询114, 同时在国外查询8.8.8.8, 当二者都只返回一个ip且相同时, 表明无需再用114, 剔除这部份url,得到lite_accelerated-domains.china.conf. 
这种精简未考虑实际使用中dns的查询时间: 如有些NS在大陆的url用国内nameserver(如114)查询更快, 但是dnsmasq设缓存后这种影响已经不大了, 这个精简版的优势是数量不多, 不到5k行, 路由器压力小. 
P.s. 这种配置基于默认所有dns query走权威nameserver(如dnscrypt-proxy), 国内部分独立出来走114以返回较快的ip. 
有人有精力的话可以维护更新一下,保持和accelerated-domains.china.conf的同步更新.

**Comment by halftan** [comment]
👍

**Comment by felixonmars** [comment]
我之所以把那部分域名也加入，是因为用8.8.8.8等境外DNS解析失败率比较高，或解析比较慢。相比之下，本地多添加几万条dnsmasq规则则并没有可感地影响解析速度。如果有这种需要（如路由器使用），欢迎维护 :)

**Comment by felixonmars** [comment]
另外需要注意的是，有（不少）的域名存在子域名才有 CDN 的情况，而因为其 NS 在境内，这边的列表里加入了整个主域名。测试的话，可能不太容易判断这种情况。

**Comment by llpub** [comment]
感谢felixonmars提醒, 

> 子域名才有 CDN 的情况

确实没考虑到, 不过现在也没有方法避免这个问题. 
如果这种情况能在原始的accelerated-domains.china.conf里标注出来就好了, 方便做精简测试
