### ISSUE TITLE
删除dmhy.org

### ISSUE THREAD

**Issue by cokebar** [felixonmars/dnsmasq-china-list#153]
我使用脚本自动生成带ipset的dnsmasq-china-list 结果发现dmhy异常慢，经查，其域名包含在dnsmasq-china-list中，被我的ipset规则强制直连不走代理了，于是龟速（电信）。
进一步检查解析，
···
dig @114.114.114.114 share.dmhy.org
; <<>> DiG 9.11.0-P1 <<>> @114.114.114.114 share.dmhy.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63024
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 75568e1978bdddab (echoed)
;; QUESTION SECTION:
;share.dmhy.org.                        IN      A

;; ANSWER SECTION:
share.dmhy.org.         159     IN      A       104.25.26.31
share.dmhy.org.         159     IN      A       104.25.27.31

;; Query time: 29 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Sun Jan 22 21:25:04 ?D1ú±ê×?ê±?? 2017
;; MSG SIZE  rcvd: 87
···

两个A记录均为美国IP（www.dmhy.org是一样的IP）。并且无cdn存在。故应删除

**Comment by lilydjwg** [comment]
这对 IP 好熟悉，一看就知道是 CloudFlare～我这里 CloudFlare 的速度很不稳定，有时候比优酷啥的还快，有时候必须走代理。
