### ISSUE TITLE
建议列表里删除 Apple 公司相关项

### ISSUE THREAD

**Issue by CyberLeopard** [felixonmars/dnsmasq-china-list#156]
Apple 公司的一些服务例如 app 下载、Apple Music 应该是在国内有 CDN，但国内 CDN 速度不理想，反而解析到国外 IP 通过 VPN 访问速度更快。

我在国内的很多网络下都遇到直接访问 Apple 资源很艰难的情况，这时本地网络是正常的，打开京东、163 等国内常见网站都很快。

列表里含有 Apple 公司相关网域。建议删除这些网域。

**Comment by felixonmars** [comment]
已将 apple 域名移至单独的 apple.china.conf，可选安装。

**Comment by CyberLeopard** [comment]
谢谢您！

相关域名应该还包括 apple-mapkit 系列。

**Comment by felixonmars** [comment]
Oops，疏忽了。已经改好 :)
