### ISSUE TITLE
另外一个常维护的国内域名列表

### ISSUE THREAD

**Issue by liyvhg** [felixonmars/dnsmasq-china-list#16]
这里有另外一个高手常维护的国内域名列表，如果综合在一起的话，就更全了
https://github.com/lifetyper/FreeRouter_V2/blob/master/Data/LocalDomains.conf

**Comment by milkyfox** [comment]
@felixonmars 加上这个吧！不然的话访问淘宝会慢很多

g.tbcdn.cn

**Comment by felixonmars** [comment]
@milkyfox 所有的 .cn 域名都已经用 /cn/ 这一条规则匹配了.

**Comment by milkyfox** [comment]
@felixonmars b（￣▽￣）d

**Comment by felixonmars** [comment]
这个列表已经验证完成过很久，原文件现在已经不存在，我暂时先关闭这个 issue 了。如有补充欢迎随时 reopen :)

**Comment by mygoare** [comment]
我简单抓取了 Top 500 Websites in China 的list，如下：

server=/baidu.com/114.114.114.114
server=/qq.com/114.114.114.114
server=/taobao.com/114.114.114.114
server=/so.com/114.114.114.114
server=/tmall.com/114.114.114.114
server=/360.cn/114.114.114.114
server=/sina.com.cn/114.114.114.114
server=/ifeng.com/114.114.114.114
server=/sogou.com/114.114.114.114
server=/163.com/114.114.114.114
server=/sohu.com/114.114.114.114
server=/iqiyi.com/114.114.114.114
server=/bilibili.com/114.114.114.114
server=/jd.com/114.114.114.114
server=/eastday.com/114.114.114.114
server=/weibo.com/114.114.114.114
server=/2345.com/114.114.114.114
server=/youku.com/114.114.114.114
server=/hao123.com/114.114.114.114
server=/mgtv.com/114.114.114.114
server=/eastmoney.com/114.114.114.114
server=/autohome.com.cn/114.114.114.114
server=/suning.com/114.114.114.114
server=/douban.com/114.114.114.114
server=/360kan.com/114.114.114.114
server=/360doc.com/114.114.114.114
server=/cctv.com/114.114.114.114
server=/douyu.com/114.114.114.114
server=/pcauto.com.cn/114.114.114.114
server=/fun.tv/114.114.114.114
server=/smzdm.com/114.114.114.114
server=/4399.com/114.114.114.114
server=/pptv.com/114.114.114.114
server=/bitauto.com/114.114.114.114
server=/xcar.com.cn/114.114.114.114
server=/huya.com/114.114.114.114
server=/dygod.com/114.114.114.114
server=/news18a.com/114.114.114.114
server=/china.com/114.114.114.114
server=/docin.com/114.114.114.114
server=/zhihu.com/114.114.114.114
server=/126.com/114.114.114.114
server=/toutiao.com/114.114.114.114
server=/alimama.com/114.114.114.114
server=/duba.com/114.114.114.114
server=/qihoo.com/114.114.114.114
server=/alipay.com/114.114.114.114
server=/huanqiu.com/114.114.114.114
server=/1688.com/114.114.114.114
server=/google.com/114.114.114.114
server=/weather.com.cn/114.114.114.114
server=/zol.com.cn/114.114.114.114
server=/10086.cn/114.114.114.114
server=/mama.cn/114.114.114.114
server=/tianya.cn/114.114.114.114
server=/people.com.cn/114.114.114.114
server=/microsoft.com/114.114.114.114
server=/58.com/114.114.114.114
server=/cheshi.com/114.114.114.114
server=/doc88.com/114.114.114.114
server=/ctrip.com/114.114.114.114
server=/taofen8.com/114.114.114.114
server=/youtube.com/114.114.114.114
server=/pconline.com.cn/114.114.114.114
server=/etao.com/114.114.114.114
server=/chinatax.gov.cn/114.114.114.114
server=/ccb.com.cn/114.114.114.114
server=/youth.cn /114.114.114.114
server=/dianping.com/114.114.114.114
server=/icbc.com.cn/114.114.114.114
server=/csdn.net/114.114.114.114
server=/189.cn/114.114.114.114
server=/95599.cn/114.114.114.114
server=/bing.com/114.114.114.114
server=/zhibo8.cc/114.114.114.114
server=/zhaopin.com/114.114.114.114
server=/google.cn/114.114.114.114
server=/cnblogs.com/114.114.114.114
server=/chinaz.com/114.114.114.114
server=/ali213.net/114.114.114.114
server=/fang.com/114.114.114.114
server=/2144.com/114.114.114.114
server=/cnki.net/114.114.114.114
server=/3dmgame.com/114.114.114.114
server=/anjuke.com/114.114.114.114
server=/tudou.com/114.114.114.114
server=/58che.com/114.114.114.114
server=/mi.com/114.114.114.114
server=/12306.cn/114.114.114.114
server=/51job.com/114.114.114.114
server=/52pojie.cn/114.114.114.114
server=/51credit.com/114.114.114.114
server=/hupu.com/114.114.114.114
server=/liqu.com/114.114.114.114
server=/tmall.hk/114.114.114.114
server=/120ask.com/114.114.114.114
server=/ourgame.com/114.114.114.114
server=/miui.com/114.114.114.114
server=/10010.com/114.114.114.114
server=/cntv.cn/114.114.114.114
server=/qidian.com/114.114.114.114
server=/youdao.com/114.114.114.114
server=/66law.cn/114.114.114.114
server=/msn.com/114.114.114.114
server=/hexun.com/114.114.114.114
server=/lifepointspanel.com/114.114.114.114
server=/aliyun.com/114.114.114.114
server=/wps.cn/114.114.114.114
server=/jdpay.com/114.114.114.114
server=/51bi.com/114.114.114.114
server=/msn.com.cn/114.114.114.114
server=/xywy.com/114.114.114.114
server=/boc.cn/114.114.114.114
server=/xiami.com/114.114.114.114
server=/vip.com/114.114.114.114
server=/manmanbuy.com/114.114.114.114
server=/39.net/114.114.114.114
server=/jb51.net/114.114.114.114
server=/bendibao.com/114.114.114.114
server=/xinhuanet.com/114.114.114.114
server=/cnki.com.cn/114.114.114.114
server=/le.com/114.114.114.114
server=/gamersky.com/114.114.114.114
server=/gsxt.gov.cn/114.114.114.114
server=/chsi.com.cn/114.114.114.114
server=/jrj.com.cn/114.114.114.114
server=/fliggy.com/114.114.114.114
server=/zybang.com/114.114.114.114
server=/Onlinedown.net/114.114.114.114
server=/yesky.com/114.114.114.114
server=/chinaacc.com/114.114.114.114
server=/ci123.com/114.114.114.114
server=/10jqka.com.cn/114.114.114.114
server=/miercn.com/114.114.114.114
server=/apple.com/114.114.114.114
server=/mydrivers.com/114.114.114.114
server=/geihui.com/114.114.114.114
server=/chinanews.com/114.114.114.114
server=/kugou.com/114.114.114.114
server=/ithome.com/114.114.114.114
server=/xiaohongshu.com/114.114.114.114
server=/jjwxc.net/114.114.114.114
server=/vmall.com/114.114.114.114
server=/zhanqi.tv/114.114.114.114
server=/jxnews.com.cn/114.114.114.114
server=/sina.cn/114.114.114.114
server=/haodf.com/114.114.114.114
server=/right.com.cn/114.114.114.114
server=/51test.net/114.114.114.114
server=/acfun.cn/114.114.114.114
server=/nipic.com/114.114.114.114
server=/offcn.com/114.114.114.114
server=/qichacha.com/114.114.114.114
server=/51fanli.com/114.114.114.114
server=/hc360.com/114.114.114.114
server=/qunar.com/114.114.114.114
server=/wasu.cn/114.114.114.114
server=/huawei.com/114.114.114.114
server=/it168.com/114.114.114.114
server=/alibaba.com/114.114.114.114
server=/mafengwo.cn/114.114.114.114
server=/amazon.cn/114.114.114.114
server=/gmw.cn/114.114.114.114
server=/lofter.com/114.114.114.114
server=/paypal.com/114.114.114.114
server=/shangxueba.com/114.114.114.114
server=/china.com.cn/114.114.114.114
server=/500.com/114.114.114.114
server=/huaban.com/114.114.114.114
server=/flyertea.com/114.114.114.114
server=/ximalaya.com/114.114.114.114
server=/sanguosha.com/114.114.114.114
server=/ppkao.com/114.114.114.114
server=/muchong.com/114.114.114.114
server=/cnbeta.com/114.114.114.114
server=/55haitao.com/114.114.114.114
server=/haibao.com/114.114.114.114
server=/dangdang.com/114.114.114.114
server=/zaobao.com/114.114.114.114
server=/wdzj.com/114.114.114.114
server=/yoka.com/114.114.114.114
server=/cztv.com/114.114.114.114
server=/baofeng.com/114.114.114.114
server=/weathercn.com/114.114.114.114
server=/cmbchina.com/114.114.114.114
server=/findlaw.cn/114.114.114.114
server=/xunlei.com/114.114.114.114
server=/shimo.im/114.114.114.114
server=/7k7k.com/114.114.114.114
server=/focus.cn/114.114.114.114
server=/weibo.cn/114.114.114.114
server=/aotian.com/114.114.114.114
server=/56.com/114.114.114.114
server=/kafan.cn/114.114.114.114
server=/duowan.com/114.114.114.114
server=/china.cn/114.114.114.114
server=/vogue.com.cn/114.114.114.114
server=/qichedaquan.com /114.114.114.114
server=/cr173.com/114.114.114.114
server=/64365.com/114.114.114.114
server=/11467.com/114.114.114.114
server=/sz.gov.cn/114.114.114.114
server=/che168.com/114.114.114.114
server=/cnr.cn/114.114.114.114
server=/taodocs.com/114.114.114.114
server=/tianyancha.com/114.114.114.114
server=/renren.com/114.114.114.114
server=/pingan.com/114.114.114.114
server=/shaanxi.gov.cn/114.114.114.114
server=/yxdown.com/114.114.114.114
server=/huatu.com/114.114.114.114
server=/xueqiu.com/114.114.114.114
server=/pclady.com.cn/114.114.114.114
server=/sodao.com/114.114.114.114
server=/pc6.com/114.114.114.114
server=/gome.com.cn/114.114.114.114
server=/shikee.com/114.114.114.114
server=/kuwo.cn/114.114.114.114
server=/pinduoduo.com/114.114.114.114
server=/faxuan.net/114.114.114.114
server=/vodtw.com/114.114.114.114
server=/jd.hk/114.114.114.114
server=/voc.com.cn/114.114.114.114
server=/eol.cn/114.114.114.114
server=/jiayuan.com/114.114.114.114
server=/mtime.com/114.114.114.114
server=/ganji.com/114.114.114.114
server=/liepin.com/114.114.114.114
server=/meituan.com/114.114.114.114
server=/ruiwen.com/114.114.114.114
server=/guancha.cn/114.114.114.114
server=/www.gov.cn/114.114.114.114
server=/wmxa.cn/114.114.114.114
server=/co188.com/114.114.114.114
server=/lenovo.com.cn/114.114.114.114
server=/cpta.com.cn/114.114.114.114
server=/e23.cn/114.114.114.114
server=/zjol.com.cn/114.114.114.114
server=/huihui.cn/114.114.114.114
server=/122.gov.cn/114.114.114.114
server=/chengdu.gov.cn/114.114.114.114
server=/feng.com/114.114.114.114
server=/biquge.cc/114.114.114.114
server=/51cto.com/114.114.114.114
server=/jiankang.com/114.114.114.114
server=/ecitic.com/114.114.114.114
server=/1905.com/114.114.114.114
server=/hebtv.com/114.114.114.114
server=/19lou.com/114.114.114.114
server=/110.com/114.114.114.114
server=/tvmao.com/114.114.114.114
server=/southcn.com/114.114.114.114
server=/hjenglish.com/114.114.114.114
server=/bidcenter.com.cn/114.114.114.114
server=/tiexue.net/114.114.114.114
server=/liuxue86.com/114.114.114.114
server=/southmoney.com/114.114.114.114
server=/58pic.com/114.114.114.114
server=/downxia.com/114.114.114.114
server=/xmfish.com/114.114.114.114
server=/sf-express.com/114.114.114.114
server=/bankcomm.com/114.114.114.114
server=/qianqian.com/114.114.114.114
server=/dilidili.name/114.114.114.114
server=/mediav.com/114.114.114.114
server=/xuexila.com/114.114.114.114
server=/sinopecsales.com/114.114.114.114
server=/wikipedia.org/114.114.114.114
server=/thepaper.cn/114.114.114.114
server=/okooo.com/114.114.114.114
server=/iwan4399.com/114.114.114.114
server=/amap.com/114.114.114.114
server=/yjbys.com/114.114.114.114
server=/vivo.com.cn/114.114.114.114
server=/dongao.com/114.114.114.114
server=/xiachufang.com/114.114.114.114
server=/biquge.la/114.114.114.114
server=/apta.gov.cn/114.114.114.114
server=/chushou.tv/114.114.114.114
server=/lwzb.cn/114.114.114.114
server=/cq.gov.cn/114.114.114.114
server=/foodmate.net/114.114.114.114
server=/gushiwen.org/114.114.114.114
server=/ihuikou.net/114.114.114.114
server=/yahoo.com/114.114.114.114
server=/cib.com.cn/114.114.114.114
server=/kankan.com/114.114.114.114
server=/yixun.com/114.114.114.114
server=/tianqi.com/114.114.114.114
server=/jinshuju.net/114.114.114.114
server=/weiyun.com/114.114.114.114
server=/youlai.cn/114.114.114.114
server=/uc.cn/114.114.114.114
server=/zongheng.com/114.114.114.114
server=/koolearn.com/114.114.114.114
server=/amazon.com/114.114.114.114
server=/cfan.com.cn/114.114.114.114
server=/jzb.com/114.114.114.114
server=/lawtime.cn/114.114.114.114
server=/wifibanlv.com/114.114.114.114
server=/55188.com/114.114.114.114
server=/tencent.com/114.114.114.114
server=/mapbar.com/114.114.114.114
server=/xiaomi.cn/114.114.114.114
server=/oschina.net/114.114.114.114
server=/qzzn.com/114.114.114.114
server=/chunyuyisheng.com/114.114.114.114
server=/kaola.com/114.114.114.114
server=/mydigit.cn/114.114.114.114
server=/jisilu.cn/114.114.114.114
server=/kuaidi100.com/114.114.114.114
server=/ahzwfw.gov.cn/114.114.114.114
server=/chinadaily.com.cn/114.114.114.114
server=/kanzhun.com/114.114.114.114
server=/kuaikanmanhua.com/114.114.114.114
server=/qiushibaike.com/114.114.114.114
server=/newsmth.net/114.114.114.114
server=/stats.gov.cn/114.114.114.114
server=/ibaotu.com/114.114.114.114
server=/hn7zz.com/114.114.114.114
server=/b2b168.com/114.114.114.114
server=/263.net/114.114.114.114
server=/mop.com/114.114.114.114
server=/faloo.com/114.114.114.114
server=/qianyan001.com/114.114.114.114
server=/mohrss.gov.cn/114.114.114.114
server=/aaqqw.com/114.114.114.114
server=/yy.com/114.114.114.114
server=/95516.com/114.114.114.114
server=/zuoche.com/114.114.114.114
server=/baixing.com/114.114.114.114
server=/znds.com/114.114.114.114
server=/sdsgwy.com/114.114.114.114
server=/yangzhou.gov.cn/114.114.114.114
server=/51240.com/114.114.114.114
server=/dzwww.com/114.114.114.114
server=/ellechina.com/114.114.114.114
server=/to8to.com/114.114.114.114
server=/cpad.gov.cn/114.114.114.114
server=/spdb.com.cn/114.114.114.114
server=/cqmmgo.com/114.114.114.114
server=/ed2000.com/114.114.114.114
server=/beihai365.com/114.114.114.114
server=/17173.com/114.114.114.114
server=/chiphell.com/114.114.114.114
server=/zcool.com.cn/114.114.114.114
server=/ftchinese.com/114.114.114.114
server=/jsform.com/114.114.114.114
server=/6.cn/114.114.114.114
server=/northnews.cn/114.114.114.114
server=/pcbaby.com.cn/114.114.114.114
server=/linkedin.com/114.114.114.114
server=/zhipin.com/114.114.114.114
server=/12371.cn/114.114.114.114
server=/dg.gov.cn/114.114.114.114
server=/21cnjy.com/114.114.114.114
server=/facebook.com/114.114.114.114
server=/chazidian.com/114.114.114.114
server=/duote.com/114.114.114.114
server=/meitu.com/114.114.114.114
server=/tsinghua.edu.cn/114.114.114.114
server=/jianke.com/114.114.114.114
server=/233.com/114.114.114.114
server=/changyou.com/114.114.114.114
server=/tuniu.com/114.114.114.114
server=/zdface.com/114.114.114.114
server=/pcbeta.com/114.114.114.114
server=/sunlandzk.com/114.114.114.114
server=/86hud.com/114.114.114.114
server=/liqucn.com/114.114.114.114
server=/chinabyte.com/114.114.114.114
server=/diyifanwen.com/114.114.114.114
server=/leju.com/114.114.114.114
server=/gdgs.gov.cn/114.114.114.114
server=/gaoxiaojob.com/114.114.114.114
server=/www.kanshu.la/114.114.114.114
server=/midea.com/114.114.114.114
server=/jingyu.com/114.114.114.114
server=/ouchn.cn/114.114.114.114
server=/adobe.com/114.114.114.114
server=/hp.com/114.114.114.114
server=/17house.com/114.114.114.114
server=/court.gov.cn/114.114.114.114
server=/smzy.com/114.114.114.114
server=/21cn.com/114.114.114.114
server=/runoob.com/114.114.114.114
server=/xueanquan.com/114.114.114.114
server=/gaokao.com/114.114.114.114
server=/xici.net/114.114.114.114
server=/iplaysoft.com/114.114.114.114
server=/taoguba.com.cn/114.114.114.114
server=/joyme.com/114.114.114.114
server=/588ku.com/114.114.114.114
server=/zxxk.com/114.114.114.114
server=/booktxt.net/114.114.114.114
server=/4399dmw.com/114.114.114.114
server=/huitu.com/114.114.114.114
server=/elecfans.com/114.114.114.114
server=/cqvip.com/114.114.114.114
server=/cmbc.com.cn/114.114.114.114
server=/hujiang.com/114.114.114.114
server=/cncrk.com/114.114.114.114
server=/lianjia.com/114.114.114.114
server=/rising.com.cn/114.114.114.114
server=/miit.gov.cn/114.114.114.114
server=/jandan.net/114.114.114.114
server=/zj.gov.cn/114.114.114.114
server=/open.com.cn/114.114.114.114
server=/cgbchina.com.cn/114.114.114.114
server=/beijing.gov.cn/114.114.114.114
server=/qingting.fm/114.114.114.114
server=/zhcw.com/114.114.114.114
server=/libaclub.com/114.114.114.114
server=/qixin.com/114.114.114.114
server=/downcc.com/114.114.114.114
server=/aicai.com/114.114.114.114
server=/piaohua.com/114.114.114.114
server=/deyi.com/114.114.114.114
server=/pcpop.com/114.114.114.114
server=/1234567.com.cn/114.114.114.114
server=/livemook.com/114.114.114.114
server=/twitter.com/114.114.114.114
server=/sxpta.com/114.114.114.114
server=/shanxi.gov.cn/114.114.114.114
server=/lss.gov.cn/114.114.114.114
server=/meishij.net/114.114.114.114
server=/guazi.com/114.114.114.114
server=/youzan.com/114.114.114.114
server=/sunlands.com/114.114.114.114
server=/xunjiepdf.com/114.114.114.114
server=/mnw.cn/114.114.114.114
server=/iqilu.com/114.114.114.114
server=/boosj.com/114.114.114.114
server=/lianzhong.com/114.114.114.114
server=/fwxgx.com/114.114.114.114
server=/dianwo98.com/114.114.114.114
server=/hebgb.gov.cn/114.114.114.114
server=/allchina.cn/114.114.114.114
server=/civilcn.com/114.114.114.114
server=/crsky.com/114.114.114.114
server=/chinatelecom.com.cn/114.114.114.114
server=/baomihua.com/114.114.114.114
server=/uc129.com/114.114.114.114
server=/freep.cn/114.114.114.114
server=/zjzwfw.gov.cn/114.114.114.114
server=/wo.cn/114.114.114.114
server=/juzimi.com/114.114.114.114
server=/vrbrothers.com/114.114.114.114
server=/tgbus.com/114.114.114.114
server=/trylist.com/114.114.114.114
server=/iteye.com/114.114.114.114
server=/8684.cn/114.114.114.114
server=/fanhuan.com/114.114.114.114
server=/ccbp.org.cn/114.114.114.114
server=/icourse163.org/114.114.114.114
server=/i4.cn/114.114.114.114
server=/jia.com/114.114.114.114
server=/alitrip.com/114.114.114.114
server=/juqingba.cn/114.114.114.114
server=/jobui.com/114.114.114.114
server=/9ku.com/114.114.114.114
server=/7y7.com/114.114.114.114
server=/upc.edu.cn/114.114.114.114
server=/safe.gov.cn/114.114.114.114
server=/hualongxiang.com/114.114.114.114
server=/178.com/114.114.114.114
server=/w3school.com.cn/114.114.114.114
server=/kujiale.com/114.114.114.114
server=/mofcom.gov.cn/114.114.114.114
server=/yue365.com/114.114.114.114
server=/chinabroadcast.cn/114.114.114.114
server=/neea.edu.cn/114.114.114.114
server=/rednet.cn/114.114.114.114
server=/steampowered.com/114.114.114.114
server=/maishoudang.com/114.114.114.114
server=/kaixin001.com/114.114.114.114
server=/psbc.com/114.114.114.114
server=/hsbank.cc/114.114.114.114
server=/pinggu.org/114.114.114.114
server=/bjrbj.gov.cn/114.114.114.114
server=/uzzf.com/114.114.114.114
server=/meishichina.com/114.114.114.114
server=/nga.cn/114.114.114.114
server=/androidin.net/114.114.114.114
server=/yinyuetai.com/114.114.114.114
server=/qyer.com/114.114.114.114
server=/netease.com/114.114.114.114
server=/chinapay.com/114.114.114.114
server=/ceair.com/114.114.114.114
server=/xinshipu.com/114.114.114.114
server=/zhulong.com/114.114.114.114
server=/51.com/114.114.114.114
server=/chinahr.com/114.114.114.114
server=/sui.com/114.114.114.114
server=/etest.net.cn/114.114.114.114
server=/duitang.com/114.114.114.114
server=/go007.com/114.114.114.114
server=/hebnews.cn/114.114.114.114
server=/cncn.com/114.114.114.114
server=/whu.edu.cn/114.114.114.114
