### ISSUE TITLE
加白名单后，音悦台的所有mv都无法播放了

### ISSUE THREAD

**Issue by uragasit** [felixonmars/dnsmasq-china-list#165]
http://www.yinyuetai.com/
随便点一个：http://v.yinyuetai.com/video/3019051?f=SY-MKDT-MVSB-1，就显示视频需要缓冲，请耐心等待的字样
取消白名单后正常

**Comment by felixonmars** [comment]
我这里没有问题，可能和你的ISP/DNS组合，或者CDN节点有关。

**Comment by Jxmn** [comment]
你把114改成你自己的dns
