### ISSUE TITLE
能不能添加apple news的地址？

### ISSUE THREAD

**Issue by lunarjoll** [felixonmars/dnsmasq-china-list#167]
我实验了一下午，一直失败。
在ios10 上面 只要添加gspe1-ssl.ls.apple.com 就可以正常使用。
但更新了11以后。一直失败。

问一句，如果解析回来的是cname，那cname地址会添加到dnsmasq吗？

**Comment by lunarjoll** [comment]
我添加了 /apple/ /icloud/  都无法使用，如果谁有兴趣的话 继续实验。
路由器设置后可以1.关闭app 2.重启iphone/ipad 的wifi 更新设置。

**Comment by lunarjoll** [comment]
下面是实验步骤
tcpdump udp 53 and host 192.168.x.x >  xxx.txt
重启ipad机器或重启ipad的wifi  
添加扫描到的网址到dnsmasq。
/etc/init.d/dnsmasq restat
实验结果：在添加  /apple/ /icloud/  后仍然无法使用。添加/.com/后正常使用。
实验结论：可能是apple.com返回的是cname地址，而cname地址结果无法使用ipset。

**Comment by lilydjwg** [comment]
`/apple/` 匹配 `*.apple` 和 `*.*.apple` 和 `*.*.*.apple`……不匹配 `gspe1-ssl.ls.apple.com` 它们。

**Comment by felixonmars** [comment]
用 dnsmasq 转发请求到其它递归解析服务器的时候无需考虑 CNAME 问题，用 unbound 等本地递归解析服务器则需要，这是我以前测试的结果。

dnsmasq 的规则是按 FQDN 匹配全部下级，即 `/com/` 匹配全部 `*.com`、`*.*.com` 等。因此 `/apple.com/` 即可匹配全部 `*.ls.apple.com`。

猜测你遇到的可能是直接请求了其他的苹果域名，如 `*.ls-apple.com`、`*.cdn-apple.com` 等。我这里没有苹果设备，因此无从测试。

**Comment by lunarjoll** [comment]
帖子我好像发错位置了。 我是想把地址加到转发名单的。 不过很高兴被解答。
