### ISSUE TITLE
配置完成及生效后的疑问

### ISSUE THREAD

**Issue by Dcryfm** [felixonmars/dnsmasq-china-list#177]
当我访问国内站点时，我浏览器插件显示的服务器物理 ip 是国内的，但某些网站访问起来依然比较慢，然后我 ping 百度，200 多的延时，ping 谷歌 90多，到底生效了吗？

**Comment by halfu** [comment]
这个列表负责将国内的常用域名使用国内的DNS服务器来解析，具体有没有生效，你可以使用dig和nslookup命令来测试。ping结果跟该列表没有直接联系，由路由决定，建议使用traceroute来检测对应ip的路由。国内外IP分开路由可使用[chnroutes](https://github.com/fivesheep/chnroutes)

**Comment by Dcryfm** [comment]
@halfu 能请教下 `chnroutes` 的使用方法不，我照着 `readme` 文件操作配置文件后，再导入到 `openvpn` 时会提示我配置文件无效。

**Comment by Dcryfm** [comment]
没啥事了。
