### ISSUE TITLE
能不能增加 dnscrypt-proxy 2.0x的forwarding_rules支持？

### ISSUE THREAD

**Issue by JunShine** [felixonmars/dnsmasq-china-list#180]
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-forwarding-rules.txt
好像很简单的样子......

**Comment by Chinian** [comment]
https://github.com/CNMan/dnscrypt-proxy-config
这个能满足你的要求吗？不过我自己用上之后似乎不管用，不知道是哪的问题

**Comment by JunShine** [comment]
我看看，这个好像可以
