### ISSUE TITLE
Please remove this domain from China mainland domains list

### ISSUE THREAD

**Issue by Loyalsoldier** [felixonmars/dnsmasq-china-list#185]
The domain `loyalsoldier.me` was my personal blog.

Unfortunately it was poisoned by the GFW since October 2017. And I had changed its NameServer to GoDaddy. Please remove it from the China mainland domains list so that people could resolved the right IP address from the upstream. Though the blog is offline right now.

Thanks a lot!

**Comment by felixonmars** [comment]
Removed :)
