### ISSUE TITLE
find_redundant.py not working

### ISSUE THREAD

**Issue by eternal-flame-AD** [felixonmars/dnsmasq-china-list#201]
I don't have much idea about what kind of redundant this script is dealing for but I found that it can't even detect a simple repetition. I think the problem worth a fix because it could prevent problems like #194 in the future.

**Comment by felixonmars** [comment]
I guess it was used to detect cases like `subdomain.foo.com` when `foo.com` is already in the list.

**Comment by felixonmars** [comment]
I have updated it in c2510c2e2c3f3b8bc79570bfa4fc6d97df9242d5, so it should now be able to detect full duplicates.
