### ISSUE TITLE
這個華為手機Google Play的變態域名 services.googleapis.cn  是如何處理的

### ISSUE THREAD

**Issue by moralrebuild** [felixonmars/dnsmasq-china-list#204]
我的LEDE上配置是：

  server=/cn/114.114.114.114

顯然此處錯誤的將它處理為國內域名，我目前通過下面命令追加了一個單獨文件：

echo 'server=/.googleapis.cn/127.0.0.1#5353' > /etc/dnsmasq.d/huawei_googleplay.conf

儘管似乎是可以使用了。但我不了解dnsmasq對這樣的域名處理是不是遵循最長/最佳(longest match) 匹配原則 ，不然的話，那這種方法的解析結果是不確定的。

請大家提供指教。

**Comment by felixonmars** [comment]
是最長匹配的。你可以去掉前面的點，直接這樣：
```
server=/googleapis.cn/127.0.0.1#5353
```

不過這個爲何需要解析到國外？

**Comment by moralrebuild** [comment]
謝謝答复！因為如果不解析到國外的話，不會返回正常結果。儘管這些是谷歌合法的中國IP，因為眾所周知的原因，谷歌沒有辦法在神奇的國度提供任何服務。導致華為的Google Play在智能翻牆的模式下依然無法工作。

**Comment by felixonmars** [comment]
好吧，我這裏用的國產 ROM （一加）的谷歌框架貌似沒有這個毛病……

**Comment by moralrebuild** [comment]
一加是不錯，對LineageOS支持也友好。我目前以谷歌親兒子為主（不排除以後考慮體驗一下那些可以刷LineageOS的國產手機）。遇到此類問題的包括銷量巨大的華為和小米手機。下面是機友的討論:
https://cn.club.vmall.com/thread-11530446-6-1.html
http://www.miui.com/thread-15970656-1-1.html

**Comment by wangw469** [comment]
@moralrebuild 解决了我华为手机应用市场用不了的问题，多谢。
