### ISSUE TITLE
translate.googleapis.com 加入白名单.

### ISSUE THREAD

**Issue by zw963** [felixonmars/dnsmasq-china-list#220]
这个地址被 [命令行下的翻译工具](https://github.com/soimort/translate-shell) 执行翻译.
我发现他速度相当好(上海电信), 甚至远远快于 bing 提供的翻译接口.

但是这个地址并没有被加入白名单.

谢谢.

**Comment by xlighting2017** [comment]
这个是 google系的域名，在 google.china.conf 里面

**Comment by zw963** [comment]
好吧, 我部署时, 使用自动化脚本下载的, 根本没 care 到这个文件 ......

谢谢.
