### ISSUE TITLE
希望能对现有列表条目的有效性进行周期性验证

### ISSUE THREAD

**Issue by SeaHOH** [felixonmars/dnsmasq-china-list#230]
很多域名的 nameserver 会不断改变，也许就不再是国内的，可能会导致域名无法正常访问。

鉴于引用此仓库的地方太多，是否有对整个列表进行周期性的验证？如果没有，能否增加这一过程？

补个之前的，开了个 issues #223 ，单纯就是想问一下如何收集域名本身，也就是原始的域名数据来源，并非是如何建立本仓库的教学。
我不知道该从何处可以获得网络上最新的、可用的、较为齐全的域名列表，希望能解答下，给个思路也行。
谢谢了！

**Comment by felixonmars** [comment]
目前基本是自己访问到的记录下来，并欢迎 PR，没有其他来源。验证要首先增加 metadata 以分类，暂时还没有做。

**Comment by SeaHOH** [comment]
了解，我试试直接解析 NS 记录来验证。
以 10 秒一个的频率，一个星期就能完成一轮，不断运行；
或者用更高的频率，一至四星期运行验证一次。

**Comment by felixonmars** [comment]
我在仓库里添加了一个简单的 verify.py 和几个列表，目前是每次随机抽取 100 个域名进行验证。
随便跑了几次，已经找到几十项失效域名并删除。

**Comment by SeaHOH** [comment]
太感谢了！
这样一段时间后，效果会好很多，也不用自己重复处理了。

**Comment by SeaHOH** [comment]
发现

**Comment by SeaHOH** [comment]
现在 verify.py 是直接用比较的方式匹配 NS，需不需要采用域名匹配方式？
这样 whitelist 就可以直接写`.cn`.，而不需要添加更多的 CN 条目。

觉得可行的话，等会儿 RP 个。

**Comment by felixonmars** [comment]
因为有些 .cn 的 NS 并不一定在国内，所以里面只留了比较靠谱的部分，剩下的 verify.py 会根据 chnroutes 自动判断 :)

**Comment by SeaHOH** [comment]
原来如此，还有个 chnroutes 判断，之前没仔细看呢。 :smile_cat:
