### ISSUE TITLE
Consider add gitlab to one special whitelist?

### ISSUE THREAD

**Issue by zw963** [felixonmars/dnsmasq-china-list#235]
Fine, i know, this project should be add all china located DNS, but, 
some famous domain, e.g. gitlab, it not blocked by GFW.
i think we should add a file, just for those not located in china, but
speed is ok domain, and we can parse this special whitelist, and
add ips into iptables, and make traffic to this site not use proxy.

Thanks.

**Comment by felixonmars** [comment]
"speed is ok" is very subjective and has additional complexity due to the nature of different ISP/locations. I don't think it is maintainable as I don't use it that way.
