### ISSUE TITLE
列表内有很多重复的项

### ISSUE THREAD

**Issue by dackdawn** [felixonmars/dnsmasq-china-list#247]
比如说qq.com(38599行)就已经包含了imqq.com(26413行)、jishuqq.com(28164行)

为什么还要保留这些域名呢？

我删了重复的域名后可以节省将近一万的项目

建议删掉那些重复的域名吧，否则会消耗大量的时间来遍历

ps：find_redundant.py这个是用来查重的吗？恕我看不懂python，我自己写了个c++来清楚重复的域名的。而且这个文件好像也运行不了，提示

```
  File "find_redundant.py", line 21
    print(f"Redundant found: {domain}")
                                     ^
SyntaxError: invalid syntax
```

**Comment by felixonmars** [comment]
这个包含关系不成立的，qq.com只能包括qq.com和*.qq.com，不是纯文本匹配。

下面的错误是因为你的 Python 不够新。

**Comment by dackdawn** [comment]
原来如此，刚刚试了一下，还真是这样，看来以前被别人误导了

刚刚更新了一下python，现在没问题了
谢谢！
