### ISSUE TITLE
在OpenWrt上无法使用自动安装

### ISSUE THREAD

**Issue by dobetter** [felixonmars/dnsmasq-china-list#257]
想使用自动安装：
root@OpenWrt:/tmp# sh install.sh 
install.sh: line 5: syntax error: unexpected "("
root@OpenWrt:/tmp# 

第五行：
SERVERS=(114.114.114.114 114.114.115.115 180.76.76.76)

提示这个( 字符错误。

**Comment by kid-oh** [comment]
一样 请问怎么解决
