### ISSUE TITLE
更新编码URL后需要用户名密码了，没办法自动安装了

### ISSUE THREAD

**Issue by hehh2001** [felixonmars/dnsmasq-china-list#285]
你好，感谢你的工作，这次更新后，用自动安装方式需要用户名密码了

**Comment by felixonmars** [comment]
抱歉，在腾讯云自动迁移到新版 coding 后我没有详细测试，看起来好像无法设置公开仓库了。我已经修改安装工具默认使用 gitee 了。

**Comment by hehh2001** [comment]
问题解决了，谢谢，其实自行手动也可以，只是自动处理方式还是比较方便简单。再次感谢你的工作！！！！！！！！！

**Comment by felixonmars** [comment]
不客气 😼
