### ISSUE TITLE
Please remove following domains

### ISSUE THREAD

**Issue by Loyalsoldier** [felixonmars/dnsmasq-china-list#293]
```
103.com
123cha.com
95081.com
airasia.com
baid.us
baidu.jp
bussou.com
busytrade.com
cnpolitics.org
dm530.net
duanzhihu.com
dysfz.cc
galaxymacau.com
galstars.net
geo.kaspersky.com
haitum.com
jiaoyou8.com
laonanren.com
mysinablog.com
ntrqq.com
nytlog.com
shuangtv.net
suppig.net
xclient.info
xjp.cc
yanghengjun.com
ydy.com
yslang.com
```

BTW, is it possible to resolve every domain in the list every week/month to avoid outdated results?

**Comment by felixonmars** [comment]
They are valid domains for the Chinese NS rule. I run verify.py every day to recheck the list.

**Comment by Loyalsoldier** [comment]
But theirs resolved IPs are either empty or outside mainland China.

**Comment by felixonmars** [comment]
Resolving domains with Chinese NS servers with a Chinese public resolver is still a speedup. Also, a matched domain's all subdomains are included too so the root domain doesn't have to be resolvable.
