### ISSUE TITLE
关于所有的cn域名都已经匹配的问题，是edu.cn也等于匹配了吗？

### ISSUE THREAD

**Issue by qwerttvv** [felixonmars/dnsmasq-china-list#296]
项目说明里说cn的域名都匹配了，看到有一条server=/cn/114.114.114.114

就是chinadns ng的chnlist用的是大佬的accelerated-domains.china.conf，但是实际使用上有一些问题

问题，，，，问题比较复杂，我怕我也说不太清楚，具体的过程麻烦大佬看一下下边这个issues
https://github.com/zfl9/chinadns-ng/issues/41

**Comment by felixonmars** [comment]
是，遵循域名匹配规则的DNS resolver（dnsmasq、unbound、smartdns等）都能匹配到，如果有其他项目不能匹配，可能不在本项目的目标用法里。

**Comment by qwerttvv** [comment]
大佬，我看了一下，是路由的脚本处理，转换了一下，

```
server=/cn.msi.com/114.114.114.114
server=/cn.net/114.114.114.114
server=/cn.pandora.net/114.114.114.114
server=/cn.vc/114.114.114.114
server=/cn.windowssearch.com/114.114.114.114
server=/cn/114.114.114.114
server=/cn0-6.com/114.114.114.114
server=/cn00.com/114.114.114.114
server=/cn006.com/114.114.114.114
server=/cn010w.com/114.114.114.114
server=/cn029.com/114.114.114.114
```

变成了

```
cn.msi.com
cn.net
cn.pandora.net
cn.vc
cn.windowssearch.com
cn0-6.com
cn00.com
cn006.com
cn010w.com
cn029.com
```

就是cn那个被吃掉了，看记录的条数，也看到74920少了一个变成74919

能不能请求大佬，多加几行，这样儿被吃掉的也少一些，先对付着，完了我再问问看看这个转的过程
中怎么吃掉的……可以吗？
```
server=/cn/114.114.114.114
server=/com.cn/114.114.114.114
server=/net.cn/114.114.114.114
server=/gov.cn/114.114.114.114
server=/edu.cn/114.114.114.114
server=/org.cn/114.114.114.114
```

**Comment by felixonmars** [comment]
这样解决问题是肯定不能接受的。什么脚本处理掉了一行？本项目提供的 Makefile 没有这个问题。

**Comment by qwerttvv** [comment]
> 这样解决问题是肯定不能接受的。什么脚本处理掉了一行？本项目提供的 Makefile 没有这个问题。

脚本那边，暂时联系不上，我再联系联系

麻烦大佬了，很感谢你这个项目

**Comment by qwerttvv** [comment]
临时性解决了，写道dnsmasq配置里了……
