### ISSUE TITLE
Pi-Hole list

### ISSUE THREAD

**Issue by aNerdgirl** [felixonmars/dnsmasq-china-list#308]
Dear all,
my question is a little of topic, but since the people reading here are experts on this topic and my chinese is very limited (learning, but only HSK2 at the moment):
I trun a pi-hole and I am looking for a good list which is maintained and blocks chinese advertisement and telemetry/tracking.
Is there a specific list for chinese domains?

Thanks! And again, sorry for the off topic question!

**Comment by popu125** [comment]
That's really off topic.

You may like these projects:
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://github.com/neoFelhz/neohosts

**Comment by aNerdgirl** [comment]
Thank you very much for helping, even though it was very off topic!
Thank you!
