### ISSUE TITLE
列表拆分

### ISSUE THREAD

**Issue by muink** [felixonmars/dnsmasq-china-list#313]
可否把 `仅国内的内容提供商` 和 `国内可访问的国外内容提供商` 的域名拆分为不同文件

`仅国内的内容提供商` 列表只要做到 **国内域名国内解析** 和 **国内cdn国内解析** 即可
这样既可以缩减列表数量保持可靠性又能避免混合 `国内可访问的国外内容提供商` 导致的cdn分配问题

比如现有列表的 `client-download.steampowered.com` 就是一个明显的例子
在使用代理的情况下这个域名依然会被通过, 导致使用代理去访问国内的节点

**Comment by felixonmars** [comment]
`国内可访问的国外内容提供商`怎么定义？

这个列表是配合路由规则用的，和代理在原理上就不能很好配合。

**Comment by muink** [comment]
或者换个说法 `明确为国内提供商` 列表和 `在国内有加速节点` 列表
`明确为国内提供商` 主要存放国内主要网络服务域名列表
`其他国内可访问` 存放那些在国内有加速节点的域名
也就是介绍里这段: 
> The domain will resolve to an IP located in China mainland when using a Chinese DNS server, but not always do when using a foreign DNS server.

**Comment by felixonmars** [comment]
这两个定义有很大范围重叠，而且经常会出现前者的子域名才满足后者定义，所以分开会增加大量重复条目并使得自动化变得麻烦。

**Comment by muink** [comment]
那是否能够生成一个列表是
在海外有加速节点但属于国内网络服务的域名？

**Comment by felixonmars** [comment]
我没有这样的测试环境和动机，如果有需要可以考虑自己实现。

**Comment by muink** [comment]
好吧，有什么方法能够收集这些国内域名吗
