### ISSUE TITLE
请添加Google FCM服务器域名

### ISSUE THREAD

**Issue by om2mo** [felixonmars/dnsmasq-china-list#317]
FCM服务器没有被墙，请添加mtalk.google.com以及它的替代域名
alt1-mtalk.google.com
...
alt8-mtalk.google.com
这些可以强制走国内DNS

因为Shadowsocks服务器与客户端有超时重连，连接FCM会有超时重连的问题

**Comment by felixonmars** [comment]
这个项目不考虑解析结果不在境内的域名，抱歉。
