### ISSUE TITLE
apple.china.conf需增加akamaiedge.net

### ISSUE THREAD

**Issue by yuanhaoliang** [felixonmars/dnsmasq-china-list#320]
` dig testflight.apple.com

; <<>> DiG 9.10.6 <<>> testflight.apple.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7241
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;testflight.apple.com.		IN	A

;; ANSWER SECTION:
testflight.apple.com.	2175	IN	CNAME	testflight.apple.com.edgekey.net.
testflight.apple.com.edgekey.net. 15409	IN CNAME e2490.dscf.akamaiedge.net.
e2490.dscf.akamaiedge.net. 27	IN	A	96.17.140.55

;; Query time: 60 msec
;; SERVER: 
;; WHEN: Fri Aug 14 15:35:14 CST 2020
;; MSG SIZE  rcvd: 150`

akamaiedge.net这个cdn域名没有在apple.china.conf
建议增加

**Comment by felixonmars** [comment]
`testflight.apple.com` 不在列表中，没有国内节点。
