### ISSUE TITLE
请从accelerated-domains.china.conf中移除sda1.dev 

### ISSUE THREAD

**Issue by RtYkk** [felixonmars/dnsmasq-china-list#321]
https://ping.pe/p.sda1.dev
`Host: p.sda1.dev, IP: 104.27.130.238 – ARIN /20 AS13335 CLOUDFLARENET, - United States [content_delivery_network]`
解析结果为CloudFlare
谢谢

**Comment by felixonmars** [comment]
```
sda1.dev.               21599   IN      NS      f1g1ns2.dnspod.net.
sda1.dev.               21599   IN      NS      f1g1ns1.dnspod.net.
```
根域名因 NS 在境内被加入的。CF 是 anycast 所以应该没有影响？

**Comment by RtYkk** [comment]
喔，不好意思没注意根域名。我close了。
