### ISSUE TITLE
请将haiyun.me从accelerated-domains.china.conf移除

### ISSUE THREAD

**Issue by yuanlam** [felixonmars/dnsmasq-china-list#324]
我当前使用unbound做国内外分流，国内通过smartdns解析，国外通过clash的dns机制解析，发现访问haiyun.me时，用国内DNS解析会十分缓慢，如果使用clash解析，用了代理，访问速度飞快，所以可否将haiyun.me移除？

**Comment by felixonmars** [comment]
```
haiyun.me.              86400   IN      NS      f1g1ns1.dnspod.net.
haiyun.me.              86400   IN      NS      f1g1ns2.dnspod.net.
```

NS 服务器在境内，我这里从境内解析是明显快于境外的。是否是 smartdns 配置问题？（PS：我的测速配置是`speed-check-mode tcp:443,tcp:80,ping`）

**Comment by yuanlam** [comment]
> ```
> haiyun.me.              86400   IN      NS      f1g1ns1.dnspod.net.
> haiyun.me.              86400   IN      NS      f1g1ns2.dnspod.net.
> ```
> 
> NS 服务器在境内，我这里从境内解析是明显快于境外的。是否是 smartdns 配置问题？（PS：我的测速配置是`speed-check-mode tcp:443,tcp:80,ping`）

抱歉，可能是我表达有问题，并不是解析速度慢，而是解析出来的地址174.137.55.169如果用国内直连访问的话，会很慢，得用代理连接。我已经知道是哪个环节出问题了，感谢答复
