### ISSUE TITLE
Should to remove domains resolved to HK IPs or not?

### ISSUE THREAD

**Issue by Loyalsoldier** [felixonmars/dnsmasq-china-list#326]
In `accelerated-domains.china.conf` file, there are so many domains whose IP addresses are located in Hong Kong. Is it a mistake, or the IP database your are using is incorrect, or you intend to do so?

It seems that this violates the rule you declare in `README`:

> The domain will resolve to an IP located in China mainland when using a Chinese DNS server, but not always do when using a foreign DNS server (For example, CDN accelerated sites that have node in China). This however does not include those having node near China mainland, like in Japan, Hong Kong, Taiwan, etc.

One example here (I use [ipip.net](https://tools.ipip.net/dns.php) to resolve `0-gold.net`):

![image](https://user-images.githubusercontent.com/10487845/91935469-55a78600-ed20-11ea-8a7e-2011d5a48e65.png)

**Comment by felixonmars** [comment]
They matched the "NS located in China" rule:

```
0-gold.net.             86400   IN      NS      jm2.dns.com.
0-gold.net.             86400   IN      NS      jm1.dns.com.
```

```
$ dig +short jm1.dns.com
218.98.111.214
$ curl cip.cc/218.98.111.214
IP      : 218.98.111.214
地址    : 中国  福建  厦门
运营商  : dns.com

数据二  : 中国 | Zenlayer全球Anycast节点(DNS.com)

数据三  :

URL     : http://www.cip.cc/218.98.111.214
```

**Comment by Loyalsoldier** [comment]
Would you provide a list in which all domains' IPs are only located in China mainland?
