### ISSUE TITLE
[Feature] Can we add a accelerated-domains.china.conf.zip file?

### ISSUE THREAD

**Issue by leiless** [felixonmars/dnsmasq-china-list#327]
Hi, @felixonmars 

Sometimes I need to download the **accelerated-domains.china.conf** file in a script, download from GitHub takes too much time in mainland China, and the gitee mirror https://gitee.com/felixonmars/dnsmasq-china-list/raw/master/accelerated-domains.china.conf requires a login account(exceeded 1MiB limitation), which is inconvenient.

Also, download the whole repo(in zip) in gitee requires a login account.

Since gitee server located in mainland China, the download speed is good for most of the cases.

![image](https://user-images.githubusercontent.com/38041294/92982331-48348d80-f4d0-11ea-824e-4ea4a819643f.png)

As the title mentioned, can we add a zipped **accelerated-domains.china.conf** file?

Since the **accelerated-domains.china.conf** is relative big in comparision of **apple.conf** and **google.conf**.

As I tested, the compression ratio of the zipped **accelerated-domains.china.conf** is 88%, which is very decent.
```bash
$ zip -9 accelerated-domains.china.conf.zip accelerated-domains.china.conf 
  adding: accelerated-domains.china.conf (deflated 88%)

$ ls -l
total 2920
-rw-rw-r-- 1 foo foo 2662213 Sep 12 08:20 accelerated-domains.china.conf
-rw-rw-r-- 1 foo foo  325464 Sep 12 08:21 accelerated-domains.china.conf.zip

$ ls -lh
total 2.9M
-rw-rw-r-- 1 foo foo 2.6M Sep 12 08:20 accelerated-domains.china.conf
-rw-rw-r-- 1 foo foo 318K Sep 12 08:21 accelerated-domains.china.conf.zip
```

Hi, visitors, if you read thus far, please upvote for this feature if you think it's helpful in your use cases.

Implementation note
- Use Git LFS to track the zip file
- Use a CI/CD service to auto zip the file for each commit in **accelerated-domains.china.conf**

**Comment by felixonmars** [comment]
There are more mirrors listed in https://github.com/felixonmars/dnsmasq-china-list/blob/master/install.sh#L13 and at least aliyun & huawei are in China mainland.

There is also a CDN: https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/
