### ISSUE TITLE
可以加？？

### ISSUE THREAD

**Issue by Potterli20** [felixonmars/dnsmasq-china-list#332]
cdnhwc2.com
www.cdnhwc2.com
bwsglb0.com
www.wsglb0.com
bilivideo.cn
www.bilivideo.cn
biliapi.com
www.biliapi.com
zwtianshangm.com
www.zwtianshangm.com
spo-msedge.net
www.spo-msedge.net
sharepoint.com
chinamobile.com
a.msstatic.com
pcvideoaliyun.titan.mgtv.com
mgtv.com
vipcdn.mgtv.com
hitv.com
smtcdns.com
chuangcdn.com
mfm.video.qq.com
ltsydzd.qq.com
video.qq.com
live.fp.qq.com
h5cgi.video.qq.com
ltscsy.qq.com
jomodns.com
kunlunca.com
71edge.com
iqiyipic.com
video.iqiyi.com
iqiyipic.com
qy.net
msg.qy.net
shopping.ele.me
alikunlun.com
tb.ele.me
fc.ele.me
uland.taobao.com
tb.cn
taobao.com
aicdn.com
cdngslb.com
soulapp.cn
lkong.net
gplayspace.com
ourplay.net
chinaunicom.com
tdnsv6.com
dlied1.cdntips.nett
myapp.com
kunluncan.com
tbcache.com
alicdn.com
alibabadns.com
alipaydns.com
elemecdn.com
huya.com
ettdnsv.com
tencent-cloud.com
126.net
tcdnlive.com
coolapk.com
nease.net
netease.com
nstool.yqkk.link
166.com
alipaydns.com
huawei.com
shifen.com
huorong.cn
xunlei.com
taichi-app.com
qlogo.cn
gtimg.cn
jetmobo.com
bdurl.net
snssdk.com
ctobsnssdk.com
n0808.com
lanzoui.com
pglstatp-toutiao.com
cdntip.com
doubanio.com
neixin.cn
youdao.com
neixin.cn
sankuai.com
dpfile.com
www.dianping.com
cmpassport.com
meiduan.com
meiduan.net
12306.cn
smtcdns.com
pstatp.com
byteimg.com
ixigua.com
iqiyi.com
happyelements.cn
163.com
ixaochuan.cn
qpic.cn
baidu.com
mybank.cn
qq.com
ele.me
alipay.com
bilibili.com
hdslb.com
kuwo.cn
izuiyou.com
kugou.con
steampowered.com
www.sharepoint.com
www.chinamobile.com
www.mgtv.com
www.hitv.com
www.smtcdns.com
www.chuangcdn.com
www.jomodns.com
www.kunlunca.com
www.71edge.com
www.iqiyipic.com
www.iqiyipic.com
www.qy.net
www.alikunlun.com
www.tb.cn
www.taobao.com
www.aicdn.com
www.cdngslb.com
www.soulapp.cn
www.lkong.net
www.gplayspace.com
www.ourplay.net
www.chinaunicom.com
www.tdnsv6.com
www.myapp.com
www.kunluncan.com
www.tbcache.com
www.alicdn.com
www.alibabadns.com
www.alipaydns.com
www.elemecdn.com
www.huya.com
www.ettdnsv.com
www.tencent-cloud.com
www.126.net
www.tcdnlive.com
www.coolapk.com
www.nease.net
www.netease.com
www.166.com
www.alipaydns.com
www.huawei.com
www.shifen.com
www.huorong.cn
www.xunlei.com
www.taichi-app.com
www.qlogo.cn
www.gtimg.cn
www.jetmobo.com
www.bdurl.net
www.snssdk.com
www.ctobsnssdk.com
www.n0808.com
www.lanzoui.com
www.pglstatp-toutiao.com
www.cdntip.com
www.doubanio.com
www.neixin.cn
www.youdao.com
www.neixin.cn
www.sankuai.com
www.dpfile.com
www.cmpassport.com
www.meiduan.com
www.meiduan.net
www.12306.cn
www.smtcdns.com
www.pstatp.com
www.byteimg.com
www.ixigua.com
www.iqiyi.com
www.happyelements.cn
www.163.com
www.ixaochuan.cn
www.qpic.cn
www.baidu.com
www.mybank.cn
www.qq.com
www.ele.me
www.alipay.com
www.bilibili.com
www.hdslb.com
www.kuwo.cn
www.izuiyou.com
www.kugou.con
www.steampowered.com

**Comment by Potterli20** [comment]
可以把114.114.114.114改为223.5.5.5？？？，我发现223.5.5.5有加速的

**Comment by felixonmars** [comment]
除 `meiduan.net` 外均为重复或无效条目。

自定义 DNS 服务器请参考 README 中手动安装部分的 make 语法：
https://github.com/felixonmars/dnsmasq-china-list#manual-installation
