### ISSUE TITLE
apple.china.conf需增加reserve-prime.apple.com

### ISSUE THREAD

**Issue by sammimk830** [felixonmars/dnsmasq-china-list#334]
如果不加進去預約IPHONE會走了外國去的。下面的查詢結果，我是自己加了白名單的了。
; <<>> DiG 9.14.10 <<>> reserve-prime.apple.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36596
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1bb7f6fe41328c99 (echoed)
;; QUESTION SECTION:
;reserve-prime.apple.com.       IN      A

;; ANSWER SECTION:
reserve-prime.apple.com. 281    IN      CNAME   reserve-prime-cdn.origin-apple.com.akadns.net.
reserve-prime-cdn.origin-apple.com.akadns.net. 281 IN CNAME reserve-prime.apple.com.mwcname.com.
reserve-prime.apple.com.mwcname.com. 41 IN A    122.225.38.28
reserve-prime.apple.com.mwcname.com. 41 IN A    122.225.28.248
reserve-prime.apple.com.mwcname.com. 41 IN A    120.39.206.126
reserve-prime.apple.com.mwcname.com. 41 IN A    59.56.26.126
reserve-prime.apple.com.mwcname.com. 41 IN A    125.77.130.19
reserve-prime.apple.com.mwcname.com. 41 IN A    125.77.132.2
reserve-prime.apple.com.mwcname.com. 41 IN A    58.222.40.22
reserve-prime.apple.com.mwcname.com. 41 IN A    106.122.254.2
reserve-prime.apple.com.mwcname.com. 41 IN A    113.16.208.182
reserve-prime.apple.com.mwcname.com. 41 IN A    58.221.78.229

;; Query time: 48 msec
;; SERVER: 192.168.50.254#53(192.168.50.254)
;; WHEN: Mon Oct 26 14:47:50 ;; MSG SIZE  rcvd: 329

**Comment by felixonmars** [comment]
谢谢，已添加。
