### ISSUE TITLE
请移除linkedin.com

### ISSUE THREAD

**Issue by raysearcher1** [felixonmars/dnsmasq-china-list#335]
请移除linkedin.com
每次访问linkedin.com都是解析到中国的CDN，无法访问美国站等国外站点。而且中国站和美国站的显示内容是不同的。
访问中国版的linkedin可以用linkedin.cn。无需用linkedin.com

**Comment by raysearcher1** [comment]
@felixonmars  请问是否可以移除？

**Comment by felixonmars** [comment]
感谢回报，已禁用。
