### ISSUE TITLE
[讨论]提个方向，如何把cloudflare host的域名都解析到固定的几个IP上去？

### ISSUE THREAD

**Issue by zz5678** [felixonmars/dnsmasq-china-list#345]
https://github.com/badafans/better-cloudflare-ip
参考以上项目

**Comment by zz5678** [comment]
目前 cloudflare 已经被墙搞的半残废了，测试网站：https://www.mini4k.com/
用它原始指向的 IP 104.26.9.111，几乎没法访问，换了 better-cloudflare-ip 测试的 IP 后，秒开

**Comment by felixonmars** [comment]
我这里用任何cf ip效果基本没有区别。在cf没有大陆节点的情况下，这个方向和本项目的目标没什么关系……

**Comment by zz5678** [comment]
还是相当有关的，呵呵，比如直接逻辑：可以建立一个 dnsmasq-cloudflare-list 把所有 cf host 的域名集中起来，统一发布。也就相当于加一个子文件

**Comment by Sinofine** [comment]
事实上better-cloudflare-ip项目产生的优选IP因人而异：不同人通过此项目得到不同的优选IP。
此外cloudflare host的网站数不胜数，在cloudflare不提供api的情况下无从枚举——gfwlist的时代已经过去了。

**Comment by zz5678** [comment]
gfwlist 可能很落伍，但pac不会过时，这个时代过去了？怎么个说法？

另外，这事儿可以解决，发现这个项目 https://github.com/zhiyi7/gfw-pac 把域名解析成 IP 再作分流，原理上可以把所有 CF 的承载的域名都解析到质量最好的，或者是没有被封的 IP 上去
