### ISSUE TITLE
蒸汽平台补充

### ISSUE THREAD

**Issue by muink** [felixonmars/dnsmasq-china-list#346]
```
steamchina.com
pwesports.cn
pwrd-hexi.cn
wmpvp.com
shequfu.net
shequfu.com
shequfu.cn
xn--dkr447bejn.net
xn--dkr447bejn.com
xn--dkr447bejn.cn
```

另外还有一个`wmsjsteam.com`的ns是akam.net, 拥有者似乎也是Valve, 但是真正使用的子域名基本都是部署在上海江苏等地的服务器上, 不知道这些域名要怎么处理

**Comment by felixonmars** [comment]
已添加 `shequfu.net`、`shequfu.com`、`xn--dkr447bejn.net`、`xn--dkr447bejn.com`。
.cn 域名已经有规则全部 match，无需处理。

`wmsjsteam.com` 我找到的解析到国内的子域名并没有境内外解析不同的情况，目前看来可以不作处理。
