### ISSUE TITLE
能否添加Microsoft系域名

### ISSUE THREAD

**Issue by Nexus2010** [felixonmars/dnsmasq-china-list#353]
针对近期出现的微软系服务无法登录的情况，微软官微 “微软帮助和支持” 给出的解释是中国地区才出现的问题，更换DNS或网络环境可以解决。

更换网络环境不大好解决，全局改用微软系的DNS会导致其他绝大部分服务出现问题。能否将微软系的域名单列出来使用指定域名服务器。

实测发现有关登录的一个域名改DNS后速度有明显改善。
已知有关登录的域名还有   logincdn.msauth.net   login.live.com   account.live.com   acctcdn.msauth.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 114.114.114.114
服务器:  public1.114dns.com
Address:  114.114.114.114
非权威应答:
名称:    sni1gl.wpc.alphacdn.net
Addresses:  2606:2800:247:1cb7:261b:1f9c:2074:3c
          152.199.39.108
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnvzeuno.azureedge.net
          acctcdnvzeuno.ec.azureedge.net
          scdn1efff.wpc.9da5e.alphacdn.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 223.6.6.6
服务器:  public2.alidns.com
Address:  223.6.6.6
非权威应答:
名称:    sni1gl.wpc.alphacdn.net
Addresses:  2606:2800:247:1cb7:261b:1f9c:2074:3c
          152.199.39.108
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnvzeuno.azureedge.net
          acctcdnvzeuno.ec.azureedge.net
          scdn1efff.wpc.9da5e.alphacdn.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 119.28.28.28
服务器:  pdns.dnspod.cn
Address:  119.28.28.28
非权威应答:
名称:    sni1gl.wpc.alphacdn.net
Addresses:  2606:2800:247:1cb7:261b:1f9c:2074:3c
          152.199.39.108
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnvzeuno.azureedge.net
          acctcdnvzeuno.ec.azureedge.net
          scdn1efff.wpc.9da5e.alphacdn.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 8.8.4.4
服务器:  dns.google
Address:  8.8.4.4
非权威应答:
名称:    sni1gl.wpc.alphacdn.net
Addresses:  2606:2800:247:1cb7:261b:1f9c:2074:3c
          152.199.39.108
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnvzeuno.azureedge.net
          acctcdnvzeuno.ec.azureedge.net
          scdn1efff.wpc.9da5e.alphacdn.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 208.67.222.222
服务器:  resolver1.opendns.com
Address:  208.67.222.222
非权威应答:
名称:    sni1gl.wpc.alphacdn.net
Addresses:  2606:2800:247:1cb7:261b:1f9c:2074:3c
          152.199.39.108
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnvzeuno.azureedge.net
          acctcdnvzeuno.ec.azureedge.net
          scdn1efff.wpc.9da5e.alphacdn.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 1.0.0.1
服务器:  one.one.one.one
Address:  1.0.0.1
非权威应答:
名称:    standard.t-0009.t-msedge.net
Addresses:  2620:1ec:46::19
          2620:1ec:bdf::19
          13.107.213.19
          13.107.246.19
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnmsftuswe2.azureedge.net
          acctcdnmsftuswe2.afd.azureedge.net
          star-azureedge-prod.trafficmanager.net
          dual.t-0009.t-msedge.net
          t-0009.t-msedge.net
          Edge-Prod-LAXr3.ctrl.t-0009.t-msedge.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 9.9.9.9
服务器:  dns9.quad9.net
Address:  9.9.9.9
非权威应答:
名称:    standard.t-0009.t-msedge.net
Addresses:  2620:1ec:bdf::19
          2620:1ec:46::19
          13.107.246.19
          13.107.213.19
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnmsftuswe2.azureedge.net
          acctcdnmsftuswe2.afd.azureedge.net
          star-azureedge-prod.trafficmanager.net
          dual.t-0009.t-msedge.net
          t-0009.t-msedge.net
          Edge-Prod-SIN30r3a.ctrl.t-0009.t-msedge.net

C:\WINDOWS\system32>nslookup acctcdn.msauth.net 4.2.2.4
服务器:  d.resolvers.level3.net
Address:  4.2.2.4
非权威应答:
名称:    standard.t-0009.t-msedge.net
Addresses:  2620:1ec:bdf::19
          2620:1ec:46::19
          13.107.246.19
          13.107.213.19
Aliases:  acctcdn.msauth.net
          acctcdn.trafficmanager.net
          acctcdnmsftuswe2.azureedge.net
          acctcdnmsftuswe2.afd.azureedge.net
          star-azureedge-prod.trafficmanager.net
          dual.t-0009.t-msedge.net
          t-0009.t-msedge.net
          Edge-Prod-LAXr3.ctrl.t-0009.t-msedge.net

C:\WINDOWS\system32>tcping 152.199.39.108
Probing 152.199.39.108:80/tcp - No response - time=2003.037ms
Probing 152.199.39.108:80/tcp - No response - time=2012.583ms
Probing 152.199.39.108:80/tcp - Port is open - time=193.572ms
Probing 152.199.39.108:80/tcp - Port is open - time=1218.884ms

Ping statistics for 152.199.39.108:80
     4 probes sent.
     2 successful, 2 failed.  (50.00% fail)
Approximate trip times in milli-seconds (successful connections only):
     Minimum = 193.572ms, Maximum = 1218.884ms, Average = 706.228ms

C:\WINDOWS\system32>tcping 13.107.246.19
Probing 13.107.246.19:80/tcp - Port is open - time=26.754ms
Probing 13.107.246.19:80/tcp - Port is open - time=26.267ms
Probing 13.107.246.19:80/tcp - Port is open - time=22.949ms
Probing 13.107.246.19:80/tcp - Port is open - time=23.151ms
Ping statistics for 13.107.246.19:80
     4 probes sent.
     4 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 22.949ms, Maximum = 26.754ms, Average = 24.780ms

C:\WINDOWS\system32>tcping 13.107.213.19
Probing 13.107.213.19:80/tcp - Port is open - time=25.388ms
Probing 13.107.213.19:80/tcp - Port is open - time=23.762ms
Probing 13.107.213.19:80/tcp - Port is open - time=24.301ms
Probing 13.107.213.19:80/tcp - Port is open - time=24.191ms
Ping statistics for 13.107.213.19:80
     4 probes sent.
     4 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 23.762ms, Maximum = 25.388ms, Average = 24.410ms

**Comment by felixonmars** [comment]
本项目仅对解析结果在中国大陆的域名进行收录，因为其他地区/ISP的访问效果因人而异（和地区、ISP、时段、运气等都有关），不容易找到普适的标准和自动化测试方法。

在你给出的例子里，访问效果较好的 IP（13.107.213.19）在微软 anycast 段，不同ISP访问效果亦存在较大差异。由于不同境外 DNS 也不一定会一直返回这个段的结果，建议自行设置或者考虑使用 [smartdns](https://github.com/pymumu/smartdns) 等支持测速的 DNS 工具来改善体验。

附我这里对微软 anycast 段的测试结果：
![2021-03-22-230907-5c80bb](https://user-images.githubusercontent.com/1006477/112011884-a7501a80-8b63-11eb-9c80-ccbecc1df988.png)

**Comment by CoelacanthusHex** [comment]
> 
> 附我这里对微软 anycast 段的测试结果： ![2021-03-22-230907-5c80bb](https://user-images.githubusercontent.com/1006477/112011884-a7501a80-8b63-11eb-9c80-ccbecc1df988.png)

问个无关的，请问这是使用的什么工具

**Comment by felixonmars** [comment]
> 问个无关的，请问这是使用的什么工具

自建 smokeping。

**Comment by xiaorong61** [comment]
我认为微软服务还是尽量翻墙访问更好，因为有些服务在国内是阉割版或者不能用，比如 bing / bing chat
