### ISSUE TITLE
请求删除 恒天.com

### ISSUE THREAD

**Issue by phoenixxie7** [felixonmars/dnsmasq-china-list#356]
这是一个中文域名，转换成AdGuardHome的配置文件之后会出错。

**Comment by Potterli20** [comment]
这个也是无法访问的东西

**Comment by BenjaminX** [comment]
Please remove 恒天.com

**Comment by xux1217** [comment]
please delete 恒天.com.
It's cause some script that can't deal this field error.

**Comment by felixonmars** [comment]
The IDN encoded name `xn--rss99n.com` is already included. Deleted.
