### ISSUE TITLE
大陆域名补充sinaimg.cn

### ISSUE THREAD

**Issue by waahaa** [felixonmars/dnsmasq-china-list#363]
![sina](https://user-images.githubusercontent.com/41323324/120915659-93827200-c6d7-11eb-8f49-f6e1ad31e6e0.png)

**Comment by Chinian** [comment]
![image](https://user-images.githubusercontent.com/6008932/120915849-9a5db480-c6d8-11eb-99f9-ab927380347f.png)

**Comment by waahaa** [comment]
my bad
