### ISSUE TITLE
添加 cname.vercel-dns.com

### ISSUE THREAD

**Issue by ZeroClover** [felixonmars/dnsmasq-china-list#369]
vercel.com 先前在全球范围内使用 `76.76.21.21` 作为其本身和 SaaS 服务的 IP。

但是，`76.76.21.21` 在大陆的多个地区已经被针对性劣化甚至屏蔽，因此 Vercel 为大陆单独提供了一个 IP 地址。

将此 SaaS 域名交由国内 DNS 解析有助于提升大陆用户访问基于 Vercel 的服务的体验。

![image](https://user-images.githubusercontent.com/13190004/124063865-5e630880-da66-11eb-9e2c-4b7bfc196b4b.png)

**Comment by felixonmars** [comment]
这个 IP 应该是 AGA 段，在中国大陆没有节点，因此不属于本项目考虑的范围。

此外，因为 dnsmasq、smartdns 等本项目主要的目标软件不做递归解析，将 CNAME 目标加入列表几乎是无效的。
