### ISSUE TITLE
请求添加国内域名 lf3-motor.dcarstatic.com  p3.dcarimg.com

### ISSUE THREAD

**Issue by zoi50a6j** [felixonmars/dnsmasq-china-list#377]
请求添加懂车帝部分域名，打开[懂车帝官网](https://www.dongchedi.com/ )可见。
lf3-motor.dcarstatic.com
p3.dcarimg.com

**Comment by felixonmars** [comment]
![DeepinRuudunkaappaus_valitse-alue_20210824150034](https://user-images.githubusercontent.com/1006477/130612795-1d89b3ee-e746-44fe-85f5-9d9ff818b2e2.png)
