### ISSUE TITLE
DNS 服务器 180.76.76.76 异常

### ISSUE THREAD

**Issue by CyberLeopard** [felixonmars/dnsmasq-china-list#378]
Hello,

最近 180.76.76.76 服务器异常，解析国内网址例如 taobao.com 返回空的 A 记录，导致 dnsmasq 返回的值有问题无法正常访问网站。即使 dnsmasq 设置了多上游也可能会选用这个错误的解析值。

建议将该 DNS 服务器从脚本默认中移除。

Thanks.

**Comment by felixonmars** [comment]
已修改，谢谢反馈。
