### ISSUE TITLE
请求添加游戏《云图计划》（中国大陆服务器）相关域名

### ISSUE THREAD

**Issue by IsoaSFlus** [felixonmars/dnsmasq-china-list#379]
![image](https://user-images.githubusercontent.com/5125031/134749584-3440ffe4-5395-4e28-89af-b2b186cf0875.png)
`42lab.cdn.sunborngame.com` 这个域名似乎是资源下载相关，并且似乎屏蔽了中国大陆以外ip的访问，所以如果分流至代理会导致下载资源失败。

**Comment by felixonmars** [comment]
已添加，谢谢。

**Comment by IsoaSFlus** [comment]
已经用上了，蟹蟹肥猫
