### ISSUE TITLE
添加tlgslb.com域名

### ISSUE THREAD

**Issue by tenwx** [felixonmars/dnsmasq-china-list#38]
这个CDN加速域名是帝联科技的，kaspersky杀毒软件的更新地址都依赖了这个CDN，例如dnl-09.geo.kaspersky.com
另外，kaspersky.com用114解析出来的ip和google dns的也不一样

**Comment by felixonmars** [comment]
CNAME 的解析一般发生在远端服务器, 因此原域名也必须列在列表中.

我添加了下面两个规则:
```
geo.kaspersky.com
tlgslb.com
```
