### ISSUE TITLE
Tesla CN

### ISSUE THREAD

**Issue by ZeroClover** [felixonmars/dnsmasq-china-list#384]
Tesla 中国最近将全球服务器和中国服务器完全隔离开来，访问境外的 Tesla 服务器将无法获取到任何属于 Tesla CN 的账号信息。

例如 `owner-api.teslamotors.com` 在海外会解析为 `205.234.31.120`，而在大陆解析为 `54.223.37.185 `。

建议将以下域名添加到列表：

```
owner-api.teslamotors.com
streaming.vn.teslamotors.com
```

或者考虑将整个 `teslamotors.com` 添加到列表以防止未来更多的中国区专用 Endpoint。

**Comment by felixonmars** [comment]
感谢，暂时已经先添加这两个域名。
