### ISSUE TITLE
请添加www.icloud.com.cn

### ISSUE THREAD

**Issue by kinggkl** [felixonmars/dnsmasq-china-list#394]
最近使用突然发现开始跳转到.cn本地解析都为国内地址
非权威应答:
名称:    ioshost.qtlcdn.com
Addresses:  221.193.246.53
          111.206.179.229
Aliases:  www.icloud.com.cn
          icloud-cn.icloud.com.akadns.net
          icloud-cn-lb.icloud.com.akadns.net

**Comment by fernvenue** [comment]
Domain `www.icloud.com.cn` already included by `server=/cn/114.114.114.114`. Additionally, we have `server=/qtlcdn.com/114.114.114.114` that include `ioshost.qtlcdn.com`.
