### ISSUE TITLE
dnsmasq.service failed because a timeout was exceeded

### ISSUE THREAD

**Issue by wimmerX** [felixonmars/dnsmasq-china-list#398]
sudo ./install.sh后，重启dnsmasq timeout error。删除几个/etc/dnsmasq.d/下的conf文件，可以成功，请问dnsmasq会限制加载的.conf数量么？这个如何调整？

**Comment by fernvenue** [comment]
Duplicate of https://github.com/felixonmars/dnsmasq-china-list/issues/227.
