### ISSUE TITLE
猫耳FM cdn

### ISSUE THREAD

**Issue by NinjaUmbra** [felixonmars/dnsmasq-china-list#407]
static.maoercdn.com  *.maoercdn.com

**Comment by fernvenue** [comment]
Already added: https://github.com/felixonmars/dnsmasq-china-list/commit/27cef2cf2be5e04c441919db021551c13b600bd3.

**Comment by NinjaUmbra** [comment]
thx

**Comment by fernvenue** [comment]
That was a commit 19 days ago, so maybe next time you can submit an issue after checking the source code, I think this will disturb the author less :)

**Comment by NinjaUmbra** [comment]
Thanks
