### ISSUE TITLE
添加 www.gjdwzp.com

### ISSUE THREAD

**Issue by entr0pia** [felixonmars/dnsmasq-china-list#414]
![image](https://user-images.githubusercontent.com/30486766/183813652-c2746566-f897-4581-ad88-9e4516ea5713.png)

**Comment by fernvenue** [comment]
Actually, whether a domain should be added to this list doesn't depend on whether its IP address is located in mainland China.

But yeah, seems this domain's NS servers are in the white list:

```
~# dig gjdwzp.com NS +short
dns10.hichina.com.
dns9.hichina.com.
```

So add it to the list is a good idea, we can get better DNS resolution :)
