### ISSUE TITLE
添加 api.anythinktech.com

### ISSUE THREAD

**Issue by 9bingyin** [felixonmars/dnsmasq-china-list#417]
![image](https://user-images.githubusercontent.com/37502927/184872133-ae59ddd2-82f3-469b-8fd3-9a5bc387ab76.png)

**Comment by felixonmars** [comment]
感谢。同时添加了其他满足此特征的 `anythinktech.com` 子域名：

datk.anythinktech.com
tk.anythinktech.com
da.anythinktech.com
