### ISSUE TITLE
谷歌翻译的api被墙

### ISSUE THREAD

**Issue by duan-dky** [felixonmars/dnsmasq-china-list#430]
![image](https://user-images.githubusercontent.com/74866582/192740955-e7775c9e-efc2-4ced-818f-02fcf6ec7dfc.png)
*如图，今天早上发现chrome自带翻译不能用，tcpping发现translate.googleapis.com的443端口全部不通，今天才有的现象，建议添加translate.googleapis.com这个域名到代理，原规则是直连域名，请求将这个域名添加到代理*

**Comment by felixonmars** [comment]
谢谢，已移除。

**Comment by duan-dky** [comment]
嗯
