### ISSUE TITLE
Revome Domain Request for blueskyxn.com and 000714.xyz

### ISSUE THREAD

**Issue by BlueSkyXN** [felixonmars/dnsmasq-china-list#436]
Hello, I am the owner of blueskyxn.com and 000714.xyz.
 Due to the recent firewall of mainland China interfering with my transit node (forwarding overseas data sources to the CDN in mainland China through mainland optimized lines), some accesses are unstable.
 Coupled with the recent increase in the cost of traffic in mainland China, I hope to remove all my domains from the mainland China optimization list.

 The list of domain names is as follows (including all subdomains)
 blueskyxn.com
 000714.xyz

 In your project, their locations are
 https://github.com/felixonmars/dnsmasq-china-list/commit/2cde3e0da86c3a75336b337494cf4ba871b15a56
 https://github.com/felixonmars/dnsmasq-china-list/commit/4d3e9e58f6df03c03a40dd685db2cfab57507d6e

 In addition, if you know of other similar projects, I also hope to introduce them so that I can deal with them further.

**Comment by felixonmars** [comment]
Your domains still have NS servers located in China mainland (Huawei Cloud).

Please bear in mind that this project is semi-automated maintained with certain rules. At the moment the scripts are not yet capable of handling customized blacklist for this scenario (on the contrary, we are currently able to handle blacklist for CDN domains with nodes in China while the NS servers are not).

I'll leave the issue open for now until the scripts were fixed.
