### ISSUE TITLE
Please update China DNS list with ssytnet.com

### ISSUE THREAD

**Issue by licson** [felixonmars/dnsmasq-china-list#442]
I have noticed cdngslb.com have started to use a new domain ssytnet.com to service some website like 163.com and others, and the current DNS list does not include this domain, causing CDN resolving to node outside Mainland China and caused some webpage loading issues.

Please kindly add ssytnet.com to the China DNS list.

Below is some sites already in the existing list but since ssytnet.com is not in the list, the resolved IPs are not pointing to Mainland China CDN and thus caused issues when browsing pages on these domains.

![image](https://user-images.githubusercontent.com/1832745/205671217-95f90bc9-f15d-4bb8-88d2-2d87df57641b.png)
![image](https://user-images.githubusercontent.com/1832745/205671261-373c5deb-0ce8-4ccf-a364-c60b7ba8cb34.png)

**Comment by felixonmars** [comment]
Thanks, added.
