### ISSUE TITLE
Add some playstation domains, current one only works for PS4 not PS5.

### ISSUE THREAD

**Issue by Originalimoc** [felixonmars/dnsmasq-china-list#446]
action-cards-host-app.rnps.dl.playstation.net
agent-popupgui.rnps.dl.playstation.net
appinfo.dl.playstation.net
bgft.rnps.dl.playstation.net
broadcast.rnps.dl.playstation.net
codex.rnps.dl.playstation.net
compilation-disc-hub.rnps.dl.playstation.net
control-center.rnps.dl.playstation.net
cosmiccube.rnps.dl.playstation.net
elysion.rnps.dl.playstation.net
envelope2.np.dl.playstation.net
explore-hub.rnps.dl.playstation.net
feature-discovery-assets-amd.dl.playstation.net
feature-discovery-device-dialog.rnps.dl.playstation.net
g2p-dialog.rnps.dl.playstation.net
game-hub-preview-launcher.rnps.dl.playstation.net
game-hub.rnps.dl.playstation.net
gaming-lounge.rnps.dl.playstation.net
gs-sec.ww.np.dl.playstation.net
gst.prod.dl.playstation.net
home.rnps.dl.playstation.net
igc-browse.rnps.dl.playstation.net
invitation-dialog.rnps.dl.playstation.net
legal-docs.rnps.dl.playstation.net
lfps-bc.rnps.dl.playstation.net
library.rnps.dl.playstation.net
loyalty-hub.rnps.dl.playstation.net
millenniumfalcon-dialog.rnps.dl.playstation.net
millenniumfalcon.rnps.dl.playstation.net
monte-carlo.rnps.dl.playstation.net
notification-overlay.rnps.dl.playstation.net
onboard-download.rnps.dl.playstation.net
player-review.rnps.dl.playstation.net
player-selection-dialog.rnps.dl.playstation.net
ppr-bgs.rnps.dl.playstation.net
ppr-crl.rnps.dl.playstation.net
profile-dialog.rnps.dl.playstation.net
profile.rnps.dl.playstation.net
ps4-system.sec.np.dl.playstation.net
ps5-multi-bundle-ota.rnps.dl.playstation.net
psnobj.prod.dl.playstation.net
psn-rsc.prod.dl.playstation.net
qgve.dl.playstation.net
remoteplay.dl.playstation.net
rnps-peripherals-onboarding.rnps.dl.playstation.net
screen-share.rnps.dl.playstation.net
search.rnps.dl.playstation.net
service-hub-psnow.rnps.dl.playstation.net
service-hub-psplus.rnps.dl.playstation.net
settings.rnps.dl.playstation.net
sgst.prod.dl.playstation.net
system-message-client.rnps.dl.playstation.net
titlestore-preview.rnps.dl.playstation.net
trophy.rnps.dl.playstation.net
uam-fs.rnps.dl.playstation.net
uef.np.dl.playstation.net
universal-checkout.rnps.dl.playstation.net
unsupported-title-hub.rnps.dl.playstation.net
ut-service.rnps.dl.playstation.net
vulcan.dl.playstation.net
wishlist.rnps.dl.playstation.net
x-wing.rnps.dl.playstation.net

**Comment by felixonmars** [comment]
I have tested through the list, but only found the following three domains having CDN nodes in China mainland:

```
gst.prod.dl.playstation.net
sgst.prod.dl.playstation.net
vulcan.dl.playstation.net
```

Added these three for now.

**Comment by Originalimoc** [comment]
nice
