### ISSUE TITLE
ocsp.pki.goog有国内节点 请加入list

### ISSUE THREAD

**Issue by actck** [felixonmars/dnsmasq-china-list#447]
谷歌ocsp服务存在国内节点, ocsp服务如果连接不正常会导致Safari网页白屏等待

**Comment by fernvenue** [comment]
Any examples?

**Comment by actck** [comment]
"ocsp.pki.goog" is that domain, dns record map to china-ip

**Comment by fernvenue** [comment]
Seems like it is already in the list:

https://github.com/felixonmars/dnsmasq-china-list/blob/3611fddf6ebf05bf920269831e304afa001fb34a/google.china.conf#L95

Make sure you have checked the list before you open an issue.

**Comment by actck** [comment]
Sorry, i didn't expect it was in this file
