### ISSUE TITLE
accelerated-domains.china.conf修改

### ISSUE THREAD

**Issue by crysleep** [felixonmars/dnsmasq-china-list#474]
+.23img.com这个域名是个图床服务且没有R18限制。。。解析都是海外IP，直连很卡，建议移除

**Comment by fernvenue** [comment]
It appears that we should keep it for the sake of achieving the fastest resolution speed:

```
~# dig 23img.com NS +short
ent02.dnspod.com.
ent01.dnspod.com.
```

Just a quick clarification, this repository is intended for DNS purposes not proxy services :)

**Comment by crysleep** [comment]
> It appears that we should keep it for the sake of achieving the fastest resolution speed:
> 
> ```
> ~# dig 23img.com NS +short
> ent02.dnspod.com.
> ent01.dnspod.com.
> ```
> 
> Just a quick clarification, this repository is intended for DNS purposes not proxy services :)

Thank you for the reminder. I apologize for not noticing that this domain is using dnspod as its NS. In that case, this domain should indeed be kept. Thank you for closing this issue.
