### ISSUE TITLE
编辑dnsmasq.conf后dns无法解析

### ISSUE THREAD

**Issue by Anivie** [felixonmars/dnsmasq-china-list#477]
Readme中的使用教程里有这一句：
> Uncomment "conf-dir=/etc/dnsmasq.d" in /etc/dnsmasq.conf

我在我的dnsmasq.conf中没有找到`conf-dir`这句话，于是手动把它加在了这个配置文件的最后一行并重启dnsmasq，然而在重启之后，我发现任何的网站都无法解析dns了。我在readme中没有找到相关的解决方案，请问应该如何排查故障？

**Comment by fernvenue** [comment]
Could you please provide your current `dnsmasq.conf` file content?

**Comment by Anivie** [comment]
> Could you please provide your current `dnsmasq.conf` file content?

[Sure](https://gist.github.com/Anivie/954e762909a2b1c1b2edb091b2d6adef).

**Comment by fernvenue** [comment]
Have you placed `accelerated-domains.china.conf, bogus-nxdomain.china.conf (and optionally google.china.conf, apple.china.conf)` under `/etc/dnsmasq.d/`?

**Comment by Anivie** [comment]
> Have you placed `accelerated-domains.china.conf, bogus-nxdomain.china.conf (and optionally google.china.conf, apple.china.conf)` under `/etc/dnsmasq.d/`?

Thanks, I am following this [link](https://github.com/coolsnowwolf/lede/issues/2551#issuecomment-568382313) and placed the `accelerated-domains.china.conf` only, and I am try to place others to it, now they were work.
