### ISSUE TITLE
请求添加3个微软直连域名

### ISSUE THREAD

**Issue by Arunmor1510** [felixonmars/dnsmasq-china-list#486]
build.microsoft.com
learn.microsoft.com
devblogs.microsoft.com

可以验证第一个解析到上海微软云，后两个使用国内cdn

**Comment by felixonmars** [comment]
已添加，谢谢

**Comment by xiaorong61** [comment]
我认为微软服务还是尽量翻墙访问更好，因为有些服务在国内是阉割版或者不能用，比如 bing / bing chat
