### ISSUE TITLE
韵达快递

### ISSUE THREAD

**Issue by wongsyrone** [felixonmars/dnsmasq-china-list#49]
http://www.yundaex.com/

**Comment by halfu** [comment]
我这里测试114.114.114.114和8.8.8.8的解析结果都是180.153.139.91

Halfu:~ Halfu$ dig www.yundaex.com @8.8.8.8

; <<>> DiG 9.8.3-P1 <<>> www.yundaex.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17959
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.yundaex.com.        IN    A

;; ANSWER SECTION:
www.yundaex.com.    3599    IN    A    180.153.139.91

;; Query time: 1404 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Jan 30 23:33:11 2015
;; MSG SIZE  rcvd: 49

Halfu:~ Halfu$ dig www.yundaex.com @114.114.114.114

; <<>> DiG 9.8.3-P1 <<>> www.yundaex.com @114.114.114.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51699
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.yundaex.com.        IN    A

;; ANSWER SECTION:
www.yundaex.com.    414    IN    A    180.153.139.91

;; Query time: 65 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Fri Jan 30 23:33:22 2015
;; MSG SIZE  rcvd: 49




--
周维
-------------------------------------
手  机：18602340237
-------------------------------------

**Comment by felixonmars** [comment]
符合了 NS 服务器在境内这一项, 我马上加, 谢谢!
