### ISSUE TITLE
中国科学院开源软件协会

### ISSUE THREAD

**Issue by wongsyrone** [felixonmars/dnsmasq-china-list#72]
www.opencas.org
forum.opencas.org

; <<>> DiG 9.9.2-P2 <<>> www.opencas.org @114.114.114.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25893
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.opencas.org.               IN      A

;; ANSWER SECTION:
www.opencas.org.        3600    IN      A       159.226.11.160 // 北京市

; <<>> DiG 9.9.2-P2 <<>> forum.opencas.org @114.114.114.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17465
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;forum.opencas.org.             IN      A

;; ANSWER SECTION:
forum.opencas.org.      3600    IN      A       159.226.11.161

**Comment by soffchen** [comment]
这个我记得不管哪里访问都是解析到北京中国科技网的

$ dig www.opencas.org @8.8.8.8
;; ANSWER SECTION:
www.opencas.org.	3127	IN	A	159.226.11.160

$ curl ip.cn/159.226.11.160
IP：159.226.11.160 来自：北京市 中国科技网

**Comment by felixonmars** [comment]
NS 服务器在境内 (DNSPod), 所以可以添加根域名喵~
