### ISSUE TITLE
将 dl.google.com 移出列表

### ISSUE THREAD

**Issue by ym** [felixonmars/dnsmasq-china-list#73]
dl.google.com 大陆服务器下载速度很差 ... 还不如直连快

http://alibench.com/rp/4a30d2874161ea726d041e51c2f289bf

**Comment by felixonmars** [comment]
之前和小伙伴测试的时候是部分出口丢包严重, 但是有很多地方测试远比直连快, 所以没有移出列表...

现在刚测试, 我的测试机器里还是 >1M/s, 比直连快很多.

**Comment by felixonmars** [comment]
看起来稳定性不好, 不断在变, 但是带宽还是不错的.
我在你给的地址上又点了一次测试, 得到了这样的结果:
http://alibench.com/rp/201736fe2132ec53625f50cc9726ab16

**Comment by soffchen** [comment]
移除吧
我的 adsense 收入下降 3 成是最好的说明……

**Comment by felixonmars** [comment]
我想起来在家里电信访问各种网站奇慢似乎就是卡在了 adsense 上, 好吧...
一会注释掉所有的 Google 域名.
