### ISSUE TITLE
usage of dnsmasq-china-list & pdnsq

### ISSUE THREAD

**Issue by hduffddybz** [felixonmars/dnsmasq-china-list#74]
Hi! It seems that the GFW was upgrading yesterday! It is really difficult to resolve websites abroad from dns server abroad by udp querying!

So I try to use pdnsq+dnsmasq to resolve the websites abroad by tcp querying! So I use dnsmasq-china-list to help me resolving from China!

I set the /etc/dnsmasq.conf and move this project file to /etc/dnsmasq.d 
"conf-dir=/etc/dnsmasq.d" &
"server=127.0.0.1#1053"(which is pdnsq server)

but It cannot resolve the websites from home and abroad!

but using "no-resolve" and "server=127.0.0.1#1053" it does well, but it may be a little slower for Chinese websites resolving.

How to fix it?

**Comment by felixonmars** [comment]
I don't think `no-resolve` is a valid option for dnsmasq, maybe you meant `no-resolv`?

You will need `no-resolv` anyway if you are using `nameserver 127.0.0.1` in `/etc/resolv.conf`, but this is irrelative to this project or pdnsq.

I am not familiar with pdnsq so I see it as a recursive resolver that does TCP queries (just like what I use unbound for), so you should be setting all the three options you mentioned to make this a feasible solution:

```
no-resolv
conf-dir=/etc/dnsmasq.d
server=127.0.0.1#1053
```

**Comment by hduffddybz** [comment]
Thank you for your reply! But when using these three options only the websites from abroad can be resolved!Really strange!

**Comment by felixonmars** [comment]
Can you resolve the domain against 114dns itself?

If not, you can try to use another resolver for dnsmasq-china-list. 114dns should work for most cases but...

**Comment by hduffddybz** [comment]
Yes! Of course! I can resolve most websites from China for a long time!

**Comment by felixonmars** [comment]
:/ no idea then. I don't think your pdnsq setup is the problem as I use DNSCrypt already.

**Comment by heiybb** [comment]
Maybe ChinaDNS would help him out...
https://github.com/clowwindy/ChinaDNS
