### ISSUE TITLE
好像 “淘宝” 之类的站点用 它自己的 dns 会快很多？

### ISSUE THREAD

**Issue by laincat** [felixonmars/dnsmasq-china-list#76]
accelerated-domains.china.conf 用的是 114 的?

**Comment by soffchen** [comment]
项目里有 dnsmasq-update-china-list 命令哦
我个人使用是替换成运营商的 DNS

**Comment by felixonmars** [comment]
可以用提供的 dnsmasq-update-china-list 工具或者 Makefile 把 114 改为你想用的 DNS。另外我测试中阿里的 DNS 远慢于 114……

**Comment by laincat** [comment]
那看来是 局部地区 才有优化的样子。之前我也一直用 114，后来出了 223，发现打开 淘宝 快很多，当然是清了 缓存 测的。不过不清楚 现在 114 是不是有跟进了。谢谢回复，谢谢。

**Comment by Firef0x** [comment]
@laincat 你可以创建一个拉取请求啊，修改 [dnsmasq-update-china-list](https://github.com/felixonmars/dnsmasq-china-list/blob/master/dnsmasq-update-china-list) ，增加一个选项，启用的话就把百度系的网站用百度 DNS，淘宝系的网站用淘宝 DNS，域名应该不多不难实现。
