### ISSUE TITLE
Remove www.bing.com ?

### ISSUE THREAD

**Issue by sagan** [felixonmars/dnsmasq-china-list#88]
国内 DNS 解析出的 www.bing.com 指向 bing 中国版 (必应), 里面的搜索结果是经过审查的, 建议移除. 列表里已经包含 "cn.bing.com", 需要使用必应的用户可以使用这个地址.

我觉得这个列表里不应该包含哪些在中国大陆和国外解析到的IP提供的是不同的服务(经过审查的 / 未经审查的)的网站域名.

**Comment by felixonmars** [comment]
谢谢，已更新。
